DELIMITER $$

DROP PROCEDURE IF EXISTS `sp_conv_step1`$$

CREATE PROCEDURE `sp_conv_step1`(
  $ACTION_NO VARCHAR(100) CHARACTER SET euckr
  , $PARTDT INT
  , $HH varchar(2)
  , $IP VARCHAR(20) CHARACTER SET euckr
  , $ORDCODE VARCHAR(100) CHARACTER SET euckr
  , $ORDRFURL VARCHAR(200) CHARACTER SET euckr
  , $ORDPCODE VARCHAR(20) CHARACTER SET euckr
  , $ORDQTY INT
  , $ORDPRICE INT
  , $USERID VARCHAR(20) CHARACTER SET euckr
  , $MEDIA_ID VARCHAR(13) CHARACTER SET euckr
  , $MEDIA_CODE VARCHAR(13) CHARACTER SET euckr
  , $SITECODE VARCHAR(32) CHARACTER SET euckr
  , $PLATFORM VARCHAR(2) CHARACTER SET euckr
  , $ADGUBUN VARCHAR(2) CHARACTER SET euckr
  , $ADPRODUCT VARCHAR(5) CHARACTER SET euckr
  , $ACTGUBUN VARCHAR(10) CHARACTER SET euckr
  , $MCGB VARCHAR(100) CHARACTER SET euckr
  , $PNM VARCHAR(200) CHARACTER SET euckr
  , $UNAME VARCHAR(200) CHARACTER SET euckr
  , $USEX CHAR(1) CHARACTER SET euckr
  , $UPNO VARCHAR(20) CHARACTER SET euckr
  , $IN_HOUR VARCHAR(20) CHARACTER SET euckr
  , $DIRECT VARCHAR(5) CHARACTER SET euckr
  , $REGDATE VARCHAR(19)
  , $shopcon_sereal_no INT(11)
  , $shopcon_weight INT(11)
  , $LAST_CLICK_TIME VARCHAR(14) CHARACTER SET euckr
  , $MOBON_YN VARCHAR(1) CHARACTER SET euckr
  , $INFLOW_ROUTE VARCHAR(4000) CHARACTER SET euckr
  , $ITL_TP_CODE VARCHAR(2)
  , $CLICK_TP VARCHAR(1)
  )
BEGIN

	DECLARE $actgb VARCHAR(10);
	SET $actgb = $ACTGUBUN;

	IF $ADPRODUCT='ico' OR $ADPRODUCT='03' THEN 
		SET $actgb='C';
	END IF ;
	

	-- INSERT INTO status_conversion_TEST(sdate,ordcode,userid,product,gubun,sitecode,media_id,media_code,convtype,ordcnt,ordpcnt,ordprice
	-- 	, mcgb, in_hour, DIRECT, REGDATE, MOBON_YN)
	-- VALUES($PARTDT,	$ORDCODE, $USERID, $ADPRODUCT, $ADGUBUN, $SITECODE, $MEDIA_ID, $MEDIA_CODE, $actgb, 1, $ORDQTY, $ORDPRICE
	-- 	, $MCGB, $IN_HOUR, $DIRECT, $REGDATE, $MOBON_YN)
	-- ON DUPLICATE KEY UPDATE ordcnt = 1;
	
	
	INSERT INTO CONVERSION_LOG_TEST(PARTDT,IP,USERID,ORDCODE,ORDRFURL,ORDPCODE,ORDQTY,ORDPRICE,ACTION_LOG_NO,PNM,UNAME,USEX,UPNO
		, IN_HOUR, DIRECT, REGDATE, LAST_CLICK_TIME, MOBON_YN, INFLOW_ROUTE)
	VALUES($PARTDT,$IP,$USERID,$ORDCODE,$ORDRFURL,$ORDPCODE,$ORDQTY,$ORDPRICE,$ACTION_NO,$PNM,$UNAME,$USEX,$UPNO
		, $IN_HOUR, $DIRECT, $REGDATE, $LAST_CLICK_TIME, $MOBON_YN, $INFLOW_ROUTE);

	INSERT INTO CONVACT_LOG_TEST(ADACTLOG_NO,PARTDT,IP,PCODE,SHOPLOG_NO,SITECODE,MCODE,MEDIA_CODE,MEDIA_ID,K_NO,VCNT,VCNT2
		,CCNT,POINT,ACTGUBUN,ADGUBUN,ADPRODUCT,REGDATE,MCGB) 
	SELECT NO ADACTLOG_NO,PARTDT,IP,PCODE,SHOPLOG_NO,SITECODE,MCODE,MEDIA_CODE,MEDIA_ID,K_NO,VCNT,VCNT2
		,CCNT,POINT,ACTGUBUN,ADGUBUN,ADPRODUCT,REGDATE,MCGB 
	FROM ACTION_LOG_TEST
	WHERE NO = $ACTION_NO
	ON DUPLICATE KEY UPDATE CONVACTCNT=CONVACTCNT+1 ; 
	
	
	
	IF $shopcon_sereal_no!=0  THEN
		UPDATE coupon_serial_TEST
		SET coup_use_date=$PARTDT, coup_use='Y' 
		WHERE NO = $shopcon_sereal_no;

		UPDATE coupon_manager_TEST
		SET coup_ordcnt = coup_ordcnt + 1, bidding= cpd_price * ((coup_ordcnt/coup_less)*100) + $shopcon_weight
		WHERE site_code=$SITECODE ;
	END IF ;

END$$

DELIMITER ;
