
-- 테이블간 데이터 확인
SELECT 'MOB_COM_HH_STATS_INFO'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_COM_HH_STATS_INFO a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_COM_STATS_INFO', a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_COM_STATS_INFO a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_ADVER_HH_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_ADVER_HH_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_ADVER_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_ADVER_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_MEDIA_HH_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_MEDIA_HH_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_MEDIA_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_MEDIA_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_ADVER_MEDIA_HH_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_ADVER_MEDIA_HH_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_ADVER_MEDIA_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_ADVER_MEDIA_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_MEDIA_SCRIPT_HH_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_MEDIA_SCRIPT_HH_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_MEDIA_SCRIPT_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_MEDIA_SCRIPT_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_CAMP_HH_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, 0 PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, 0 MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_CAMP_HH_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_CAMP_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, 0 PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, 0 MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_CAMP_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_CAMP_MEDIA_HH_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, 0 PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_CAMP_MEDIA_HH_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_CAMP_MEDIA_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, 0 PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_CAMP_MEDIA_STATS a WHERE a.STATS_DTTM=20180517
;

SELECT 'MOB_CNVRS_HH_STATS'gubun, STATS_DTTM
	, SUM(ORDER_AMT)ORDER_AMT, SUM(ORDER_CNT)ORDER_CNT, SUM(ORDER_QY)ORDER_QY
FROM BILLING.MOB_CNVRS_HH_STATS a WHERE a.STATS_DTTM=20180517
GROUP BY STATS_DTTM
UNION
SELECT 'MOB_CNVRS_STATS'gubun, STATS_DTTM
	, SUM(ORDER_AMT)ORDER_AMT, SUM(ORDER_CNT)ORDER_CNT, SUM(ORDER_QY)ORDER_QY
FROM BILLING.MOB_CNVRS_STATS a WHERE a.STATS_DTTM=20180517 
GROUP BY STATS_DTTM
;


-- 통계공통
SELECT 'MOB_COM_STATS_INFO', a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_COM_STATS_INFO a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_ADVER_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_ADVER_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_MEDIA_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_MEDIA_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_ADVER_MEDIA_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_ADVER_MEDIA_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_MEDIA_SCRIPT_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_MEDIA_SCRIPT_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_CAMP_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, 0 PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, 0 MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_CAMP_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_CAMP_MEDIA_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, 0 PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_CAMP_MEDIA_STATS a WHERE a.STATS_DTTM=20180517
;

SELECT 'MOB_KWRD_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, 0 PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_KWRD_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT a.*, 0, 0, 0, 0
FROM (
	SELECT 'status_keywordlink'gubun, a.sdate, SUM(viewcnt)v, 0 v2, SUM(clickcnt)clickcnt, SUM(POINT)p, SUM(ppoint)mp
	FROM dreamsearch.status_keywordlink a
	WHERE a.sdate=20180517
	GROUP BY a.sdate
	UNION
	SELECT 'status_keywordlinkM'gubun, a.sdate, SUM(viewcnt)v, 0 v2, SUM(clickcnt)clickcnt, SUM(POINT)p, SUM(ppoint)mp
	FROM dreamsearch.status_keywordlink_m a
	WHERE a.sdate=20180517
	GROUP BY a.sdate
	UNION
	SELECT 'istatus_keywordlink'gubun, a.sdate, SUM(viewcnt)v, 0 v2, SUM(clickcnt)clickcnt, SUM(POINT)p, SUM(ppoint)mp
	FROM dreamsearch.istatus_keywordlink a
	WHERE a.sdate=20180517
	GROUP BY a.sdate
	UNION
	SELECT 'sstatus_keywordlink'gubun, a.sdate, SUM(viewcnt)v, 0 v2, SUM(clickcnt)clickcnt, SUM(POINT)p, SUM(ppoint)mp
	FROM dreamsearch.sstatus_keywordlink a
	WHERE a.sdate=20180517
	GROUP BY a.sdate
)a
;



-- 광고주 기준
SELECT 'MOB_ADVER_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_ADVER_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_ADVER_MEDIA_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_ADVER_MEDIA_STATS a WHERE a.STATS_DTTM=20180517
;
SELECT 'MOB_ADVER_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_ADVER_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_CNVRS_STATS'gubun, a.STATS_DTTM
	, COUNT(*) c, 0, 0, 0, 0, 0, 0, 0, 0
FROM BILLING.MOB_CNVRS_STATS a WHERE a.STATS_DTTM=20180517
;

-- 캠페인
SELECT 'MOB_CAMP_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, 0 PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, 0 MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_CAMP_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_CAMP_MEDIA_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, 0 PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_CAMP_MEDIA_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_KWRD_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, 0 PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_KWRD_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_CNVRS_STATS'gubun, a.STATS_DTTM
	, COUNT(*) c, 0, 0, 0, 0, 0, 0, 0, 0
FROM BILLING.MOB_CNVRS_STATS a WHERE a.STATS_DTTM=20180517
;


-- 매체 스크립트
SELECT 'MOB_MEDIA_SCRIPT_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_MEDIA_SCRIPT_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_ADVER_MEDIA_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_ADVER_MEDIA_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_CAMP_MEDIA_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, 0 PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_CAMP_MEDIA_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_KWRD_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, 0 PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_KWRD_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_CNVRS_STATS'gubun, a.STATS_DTTM
	, COUNT(*) c, 0, 0, 0, 0, 0, 0, 0, 0
FROM BILLING.MOB_CNVRS_STATS a WHERE a.STATS_DTTM=20180517
;


-- 모비온대사
SELECT 'MOB_COM_HH_STATS_INFO', a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_COM_HH_STATS_INFO a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_COM_STATS_INFO', a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_COM_STATS_INFO a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_ADVER_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_ADVER_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_MEDIA_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_MEDIA_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_ADVER_MEDIA_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_ADVER_MEDIA_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_MEDIA_SCRIPT_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, SUM(PAR_EPRS_CNT)PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_MEDIA_SCRIPT_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_CAMP_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, 0 PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, 0 MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_CAMP_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT 'MOB_CAMP_MEDIA_STATS'gubun, a.STATS_DTTM
	, SUM(TOT_EPRS_CNT)TOT_EPRS_CNT, 0 PAR_EPRS_CNT, SUM(CLICK_CNT)CLICK_CNT, SUM(ADVRTS_AMT)ADVRTS_AMT, SUM(MEDIA_PYMNT_AMT)MEDIA_PYMNT_AMT
	, SUM(TRGT_EPRS_CNT)TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT)TRGT_PAR_EPRS_CNT, SUM(TRGT_CLICK_CNT)TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT)TRGT_ADVRTS_AMT
FROM BILLING.MOB_CAMP_MEDIA_STATS a WHERE a.STATS_DTTM=20180517
UNION
SELECT gubun, sdate, SUM(viewcnt)viewcnt, SUM(viewcnt2)viewcnt2, SUM(clickcnt)clickcnt, SUM(p)p, 0 mp, 0 a1, 0 a2, 0 a3, 0 a4
FROM (
	SELECT 'status_sitecode'gubun, sdate, SUM(viewcnt)viewcnt, SUM(viewcnt2)viewcnt2, SUM(clickcnt)clickcnt, SUM(POINT)p
	FROM dreamsearch.status_sitecode a
	WHERE a.sdate='20180517'
	UNION
	SELECT 'istatus_sitecode'gubun, sdate, SUM(viewcnt)viewcnt, SUM(viewcnt2)viewcnt2, SUM(viewcnt)clickcnt, SUM(POINT)p
	FROM dreamsearch.istatus_sitecode a
	WHERE a.sdate='20180517'
	UNION
	SELECT 'sstatus_sitecode'gubun, sdate, SUM(viewcnt)viewcnt, SUM(viewcnt2)viewcnt2, SUM(clickcnt)clickcnt, SUM(POINT)p
	FROM dreamsearch.sstatus_sitecode a
	WHERE a.sdate='20180517'
)a
UNION
SELECT gubun, sdate, SUM(viewcnt)viewcnt, SUM(viewcnt2)viewcnt2, SUM(clickcnt)clickcnt, SUM(p)p, 0 mp, 0 a1, 0 a2, 0 a3, 0 a4
FROM (
	SELECT 'status_day_media'gubun, sdate, SUM(viewcnt)viewcnt, SUM(viewcnt2)viewcnt2, SUM(clickcnt)clickcnt, SUM(POINT)p
	FROM dreamsearch.status_day_media a
	WHERE a.sdate='20180517'
	UNION
	SELECT 'istatus_sitecode'gubun, sdate, SUM(viewcnt)viewcnt, SUM(viewcnt2)viewcnt2, SUM(viewcnt)clickcnt, SUM(POINT)p
	FROM dreamsearch.istatus_day_media a
	WHERE a.sdate='20180517'
	UNION
	SELECT 'sstatus_sitecode'gubun, sdate, SUM(viewcnt)viewcnt, SUM(viewcnt2)viewcnt2, SUM(clickcnt)clickcnt, SUM(POINT)p
	FROM dreamsearch.sstatus_day_media a
	WHERE a.sdate='20180517'
)a
;


-- 상품정보
	SELECT userid, COUNT(*)c FROM BILLING.MOB_SHOP_DATA_TEST a 
	WHERE LEFT(a.LASTUPDATE,10)='2018-04-23'
	GROUP BY a.userid
;
	SELECT userid, COUNT(*)c FROM BILLING.SHOP_DATA_TEST a
	WHERE LEFT(a.LASTUPDATE,10)='2018-04-23'
	GROUP BY a.userid
;
-- 상품정보 58
	SELECT userid, COUNT(*)c FROM MOB_SHOP_DATA a 
	WHERE LEFT(a.LASTUPDATE,10)='2018-04-23'
	GROUP BY a.userid
;
	SELECT userid, COUNT(*)c FROM SHOP_DATA a 
	WHERE LEFT(a.LASTUPDATE,10)='2018-04-23'
	GROUP BY a.userid
;



-- 삼풍통계
SELECT 'stats_shopdata_mob_TEST'gubun, a.sdate, COUNT(*)c FROM BILLING.stats_shopdata_mob_TEST a WHERE a.sdate='20180517'
UNION
SELECT 'stats_shopdata_new_TEST'gubun, a.sdate, COUNT(*)c FROM BILLING.stats_shopdata_new_TEST a WHERE a.sdate='20180517'
;
-- 삼풍통계 58
SELECT 'stats_shopdata_mob'gubun, a.sdate, COUNT(*)c FROM dreamsearch.stats_shopdata_mob a WHERE a.sdate='20180517'
UNION
SELECT 'stats_shopdata_new'gubun, a.sdate, COUNT(*)c FROM dreamsearch.stats_shopdata_new a WHERE a.sdate='20180517'
;


-- 액션로그 비교
SELECT a.*, b.*, a.c-b.c diff
FROM (
	SELECT 'billing'gubun
		, COUNT(*) c
	FROM BILLING.ACTION_LOG_TEST a 
	WHERE a.PARTDT=20180517
) a, (
	SELECT 'dream'gubun
		, COUNT(*) c
	FROM dreamsearch.ACTION_LOG a 
	WHERE a.PARTDT=20180517
) b
;



-- 회원정보 포인트
SELECT 'billing', SUM(POINT)p, SUM(MPOINT)mp
FROM BILLING.admember_TEST_20180517 a
UNION
SELECT 'dream', SUM(POINT)p, SUM(MPOINT)mp
FROM BILLING.admember_20180517 a
;


SELECT UNIX_TIMESTAMP('2018-04-15');
SELECT a.NO, a_log, FROM_UNIXTIME(a.REGDATE, '%Y-%m-%d %H:%i:%s')regdate FROM dreamsearch.mobon_history_table a 
WHERE a.a_log LIKE '%admember%point%' AND a.USE_TABLE='admember' AND FROM_UNIXTIME(a.REGDATE, '%Y%m%d') = '20180517' -- and instr(a_log, 'spash1')>0
ORDER BY 3 DESC
;

-- admember 사용포인트
SELECT 'billing', SUM(POINT)p, SUM(MPOINT)mp
FROM BILLING.admember_TEST a
UNION
SELECT 'dream', SUM(POINT)p, SUM(MPOINT)mp
FROM dreamsearch.admember a
;

-- 캠페인 사용포인트
SELECT 'billing_adsite', SUM(usemoney)usemoney, SUM(usedmoney)usedmoney
FROM BILLING.adsite_TEST_20180517 a
UNION
SELECT 'billing_iadsite', SUM(usemoney)usemoney, SUM(usedmoney)usedmoney
FROM BILLING.iadsite_TEST_20180517 a
UNION
SELECT 'dream_adsite', SUM(usemoney)usemoney, SUM(usedmoney)usedmoney
FROM BILLING.adsite_20180517 a
UNION
SELECT 'dream_iadsite', SUM(usemoney)usemoney, SUM(usedmoney)usedmoney
FROM BILLING.iadsite_20180517 a
UNION
SELECT 'billing_rtb_adsite'gubun, SUM(a.w_usedmoney)wu, SUM(a.m_usedmoney)mu
FROM BILLING.adsite_rtb_info_TEST_20180517 a
UNION
SELECT 'dream_rtb_adsite'gubun, SUM(a.w_usedmoney)wu, SUM(a.m_usedmoney)mu
FROM BILLING.adsite_rtb_info_20180517 a
;

-- 실시간 usedmoney
SELECT 'billing_adsite', SUM(usemoney)usemoney, SUM(usedmoney)usedmoney
FROM BILLING.adsite_TEST a
UNION
SELECT 'billing_iadsite', SUM(usemoney)usemoney, SUM(usedmoney)usedmoney
FROM BILLING.iadsite_TEST a
UNION
SELECT 'dream_adsite', SUM(usemoney)usemoney, SUM(usedmoney)usedmoney
FROM dreamsearch.adsite a
UNION
SELECT 'dream_iadsite', SUM(usemoney)usemoney, SUM(usedmoney)usedmoney
FROM dreamsearch.iadsite a
;
SELECT 'billing'gubun, SUM(a.w_usedmoney)wu, SUM(a.m_usedmoney)mu
FROM BILLING.adsite_rtb_info_TEST a
UNION
SELECT 'dream'gubun, SUM(a.w_usedmoney)wu, SUM(a.m_usedmoney)mu
FROM dreamsearch.adsite_rtb_info a
;


-- 컨버전로그
SELECT 'billing'gubun, COUNT(*) c
FROM BILLING.CONVACT_LOG_TEST a
WHERE a.PARTDT=20180517
UNION
SELECT 'dream'gubun, COUNT(*) c
FROM dreamsearch.CONVACT_LOG a
WHERE a.PARTDT=20180517
;

-- 컨버전 로그
SELECT 'billing'gubun, COUNT(*)c
FROM BILLING.CONVERSION_LOG_TEST a 
WHERE a.PARTDT=20180421
UNION
SELECT 'dream'gubun, COUNT(*)c
FROM dreamsearch.CONVERSION_LOG a 
WHERE a.PARTDT=20180421
;
SELECT 'billing'gubun, COUNT(*)c
FROM BILLING.MOB_CNVRS_NCL a 
WHERE a.STATS_DTTM=20180517
UNION
SELECT 'dream'gubun, COUNT(*)c
FROM dreamsearch.CONVERSION_LOG a 
WHERE a.PARTDT=20180517
;

-- 컨버전 로그
SELECT CONCAT(a.ip, '-', a.userid)k, a.ORDCODE, a.REGDATE, a.LAST_CLICK_TIME, a.MOBON_YN 
FROM CONVERSION_LOG_TEST a 
WHERE a.PARTDT=20180517
-- AND CONCAT(a.IP, '-', a.USERID) LIKE '59.29.179.203.526823%'
-- AND a.USERID='koreahrd' AND a.ORDCODE='OrdNo_201803291910'
ORDER BY a.no DESC 
;
SELECT CONCAT(a.ip, '-', a.userid)k, a.ORDCODE, a.REGDATE, a.LAST_CLICK_TIME, a.MOBON_YN 
FROM dreamsearch.CONVERSION_LOG a 
WHERE a.PARTDT=20180517
-- AND CONCAT(a.IP, '-', a.USERID) LIKE '59.29.179.203.526823%'
-- AND a.USERID='koreahrd' AND a.ORDCODE='OrdNo_201803291910'
ORDER BY a.no DESC 
;

-- 외부연동
SELECT 'billing'gubun, SUM(a.viewcnt)v, SUM(a.viewcnt_mobon)vm, SUM(a.clickcnt)c, SUM(a.clickcnt_mobon)cm, SUM(a.passback)p
FROM BILLING.external_report_TEST a
WHERE a.sdate='20180502'
UNION
SELECT 'dream'gubun, SUM(a.viewcnt)v, SUM(a.viewcnt_mobon)vm, SUM(a.clickcnt)c, SUM(a.clickcnt_mobon)cm, SUM(a.passback)p
FROM dreamsearch.external_report a
WHERE a.sdate='20180502'
UNION
SELECT 'dreamdayM'gubun, SUM(viewcnt)v, 0, SUM(clickcnt)c, 0, 0
FROM dreamsearch.status_day_media a 
WHERE a.sdate='20180502' AND a.mcode IN ( 'widerplanet','criteo','ebay02','realclick','madrealclick','google','ekbeatle','adop','mntree','ntos','iebay','realclickweb','n2ad','toast','cauly1','cpilinkage','rainbow','mcaulyi','mtheamedia','adoplow','dable1','adexinter','idn','inl11st' )
;
-- 지면별 차이
SELECT *
FROM (
	SELECT 'billing'gubun, a.media_code k, SUM(a.viewcnt)v, SUM(a.viewcnt_mobon)vm, SUM(a.clickcnt)c, SUM(a.clickcnt_mobon)cm, SUM(a.passback)p
	FROM BILLING.external_report_TEST a
	WHERE a.sdate='20180517'
	GROUP BY a.media_code
) a, (
	SELECT 'dreamex'gubun, a.media_code k, SUM(a.viewcnt)v, SUM(a.viewcnt_mobon)vm, SUM(a.clickcnt)c, SUM(a.clickcnt_mobon)cm, SUM(a.passback)p
	FROM dreamsearch.external_report a
	WHERE a.sdate='20180517'
	GROUP BY a.media_code
)b WHERE a.k=b.k AND a.vm<>b.vm
;
-- 광고주별차이
SELECT *
FROM (
	SELECT 'billing'gubun, a.userid k, SUM(a.viewcnt)v, SUM(a.viewcnt_mobon)vm, SUM(a.clickcnt)c, SUM(a.clickcnt_mobon)cm, SUM(a.passback)p
	FROM BILLING.external_report_TEST a
	WHERE a.sdate='20180517'
	GROUP BY a.userid
) a, (
	SELECT 'dreamex'gubun, a.userid k, SUM(a.viewcnt)v, SUM(a.viewcnt_mobon)vm, SUM(a.clickcnt)c, SUM(a.clickcnt_mobon)cm, SUM(a.passback)p
	FROM dreamsearch.external_report a
	WHERE a.sdate='20180517'
	GROUP BY a.userid
)b WHERE a.k=b.k AND a.vm<>b.vm
;


SELECT *
  FROM (
          WITH
		 DT AS (SELECT '20180429' DT)
        , A AS (SELECT *
                  FROM BILLING.MOB_COM_STATS_INFO
				     , DT
                 WHERE STATS_DTTM = DT.DT
               )
        , B AS (SELECT STATS_DTTM, PLTFOM_TP_CODE, ADVRTS_PRDT_CODE, ADVRTS_TP_CODE, ITL_TP_CODE
                     , SUM(TOT_EPRS_CNT) TOT_EPRS_CNT, SUM(PAR_EPRS_CNT) PAR_EPRS_CNT, SUM(CLICK_CNT) CLICK_CNT, SUM(ADVRTS_AMT) ADVRTS_AMT
                     , SUM(MEDIA_PYMNT_AMT) MEDIA_PYMNT_AMT, SUM(TRGT_EPRS_CNT) TRGT_EPRS_CNT, SUM(TRGT_PAR_EPRS_CNT) TRGT_PAR_EPRS_CNT
                     , SUM(TRGT_CLICK_CNT) TRGT_CLICK_CNT, SUM(TRGT_ADVRTS_AMT) TRGT_ADVRTS_AMT
                  FROM BILLING.MOB_COM_HH_STATS_INFO
				     , DT 
                 WHERE STATS_DTTM = DT.DT
                 GROUP BY STATS_DTTM, PLTFOM_TP_CODE, ADVRTS_PRDT_CODE, ADVRTS_TP_CODE, ITL_TP_CODE
               )
        SELECT B.STATS_DTTM, B.PLTFOM_TP_CODE, B.ADVRTS_PRDT_CODE, B.ITL_TP_CODE
             , B.TOT_EPRS_CNT      - IFNULL(A.TOT_EPRS_CNT     , 0) TOT_EPRS_CNT_DIFF
             , B.PAR_EPRS_CNT      - IFNULL(A.PAR_EPRS_CNT     , 0) PAR_EPRS_CNT_DIFF
             , B.CLICK_CNT         - IFNULL(A.CLICK_CNT        , 0) CLICK_CNT_DIFF
             , B.ADVRTS_AMT        - IFNULL(A.ADVRTS_AMT       , 0) ADVRTS_AMT_DIFF
             , B.MEDIA_PYMNT_AMT   - IFNULL(A.MEDIA_PYMNT_AMT  , 0) MEDIA_PYMNT_AMT_DIFF
             , B.TRGT_EPRS_CNT     - IFNULL(A.TRGT_EPRS_CNT    , 0) TRGT_EPRS_CNT_DIFF
             , B.TRGT_PAR_EPRS_CNT - IFNULL(A.TRGT_PAR_EPRS_CNT, 0) TRGT_PAR_EPRS_CNT_DIFF
             , B.TRGT_CLICK_CNT    - IFNULL(A.TRGT_CLICK_CNT   , 0) TRGT_CLICK_CNT_DIFF
             , B.TRGT_ADVRTS_AMT   - IFNULL(A.TRGT_ADVRTS_AMT  , 0) TRGT_ADVRTS_AMT_DIFF
          FROM A RIGHT JOIN B
            ON A.STATS_DTTM = B.STATS_DTTM
           AND A.PLTFOM_TP_CODE = B.PLTFOM_TP_CODE
           AND A.ADVRTS_PRDT_CODE = B.ADVRTS_PRDT_CODE
           AND A.ADVRTS_TP_CODE = B.ADVRTS_TP_CODE
           AND A.ITL_TP_CODE = B.ITL_TP_CODE
        ) RESULT   
 WHERE TOT_EPRS_CNT_DIFF      <> 0
    OR PAR_EPRS_CNT_DIFF      <> 0
    OR CLICK_CNT_DIFF         <> 0
    OR ADVRTS_AMT_DIFF        <> 0
    OR MEDIA_PYMNT_AMT_DIFF   <> 0
    OR TRGT_EPRS_CNT_DIFF     <> 0
    OR TRGT_PAR_EPRS_CNT_DIFF <> 0
    OR TRGT_CLICK_CNT_DIFF    <> 0
    OR TRGT_ADVRTS_AMT_DIFF   <> 0
 ORDER BY 1, 2, 3, 4
;



