-- REQ_STATS.MOB_PROCESS_HH_STATS definition

CREATE TABLE `MOB_PROCESS_HH_STATS` (
  `NO` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `STATS_DTTM` int(11) NOT NULL COMMENT '통계일자',
  `STATS_HH` varchar(2) NOT NULL COMMENT '통계일자',
  `PLTFOM_TP_CODE` varchar(2) NOT NULL COMMENT '플랫폼구분코드|MOBON_COM_CODE.PLTFOM_TP_CODE',
  `ADVRTS_PRDT_CODE` varchar(2) NOT NULL COMMENT '광고상품코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE',
  `ADVRTS_TP_CODE` varchar(2) NOT NULL COMMENT '광고구분코드|MOBON_COM_CODE.ADVRTS_TP_CODE',
  `ITL_TP_CODE` varchar(2) NOT NULL COMMENT '연동구분코드|MOBON_COM_CODE.ITL_TP_CODE',
  `REQ_CNT` int(11) DEFAULT 0 COMMENT '송출요청횟수',
  `ASK_CNT` int(11) DEFAULT 0 COMMENT '광고요구횟수',
  `RES_CNT` int(11) DEFAULT 0 COMMENT '송출응답횟수',
  `ANS_SUCC_CNT` int(11) DEFAULT 0 COMMENT '광고응답성공횟수',
  `ANS_FAIL_CNT` int(11) DEFAULT 0 COMMENT '광고응답실패횟수',
  `REG_DTTM` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록시간',
  `ALT_DTTM` datetime DEFAULT NULL COMMENT '수정시간',
  PRIMARY KEY (`NO`,`STATS_DTTM`),
  UNIQUE KEY `MOB_PROCESS_HH_STATS_UK_01` (`STATS_DTTM`,`STATS_HH`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`ITL_TP_CODE`),
  KEY `MOB_PROCESS_HH_STATS_IDX_02` (`ADVRTS_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_HH_STATS_IDX_03` (`ITL_TP_CODE`,`STATS_DTTM`)
) ENGINE=InnoDB AUTO_INCREMENT=2769818 DEFAULT CHARSET=utf8 COMMENT='요청수 시간대 통계'
 PARTITION BY RANGE (`STATS_DTTM`)
(PARTITION `MOB_PROCESS_HH_STATS_p20220601` VALUES LESS THAN (20220701) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_HH_STATS_p20220701` VALUES LESS THAN (20220801) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_HH_STATS_p20220801` VALUES LESS THAN (20220901) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_HH_STATS_p20220901` VALUES LESS THAN (20221001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_HH_STATS_p20221001` VALUES LESS THAN (20221101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_HH_STATS_p20221101` VALUES LESS THAN (20221201) ENGINE = InnoDB);


-- REQ_STATS.MOB_PROCESS_RESULT_ADSITE_CAMP_HH_STATS definition

CREATE TABLE `MOB_PROCESS_RESULT_ADSITE_CAMP_HH_STATS` (
  `NO` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `STATS_DTTM` int(11) NOT NULL COMMENT '통계일자',
  `STATS_HH` varchar(2) NOT NULL COMMENT '통계일자',
  `PLTFOM_TP_CODE` varchar(2) NOT NULL COMMENT '플랫폼구분코드|MOBON_COM_CODE.PLTFOM_TP_CODE',
  `ADVRTS_PRDT_CODE` varchar(2) NOT NULL COMMENT '광고상품코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE',
  `ADVRTS_TP_CODE` varchar(2) NOT NULL COMMENT '광고구분코드|MOBON_COM_CODE.ADVRTS_TP_CODE',
  `USERID` varchar(20) NOT NULL COMMENT '광고주아이디',
  `ITL_TP_CODE` varchar(2) NOT NULL COMMENT '연동구분코드|MOBON_COM_CODE.ITL_TP_CODE',
  `PROCESS_RESULT_CODE` varchar(2) NOT NULL COMMENT '처리유형|MOBON_COM_CODE.PROCESS_RESULT_CODE',
  `REQ_CNT` int(11) DEFAULT 0 COMMENT '송출요청횟수',
  `ASK_CNT` int(11) DEFAULT 0 COMMENT '광고요구횟수',
  `RES_CNT` int(11) DEFAULT 0 COMMENT '송출응답횟수',
  `ANS_SUCC_CNT` int(11) DEFAULT 0 COMMENT '광고응답성공횟수',
  `ANS_FAIL_CNT` int(11) DEFAULT 0 COMMENT '광고응답실패횟수',
  `REG_DTTM` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록시간',
  `ALT_DTTM` datetime DEFAULT NULL COMMENT '수정시간',
  PRIMARY KEY (`NO`,`STATS_DTTM`),
  UNIQUE KEY `MOB_PROCESS_RESULT_ADSITE_CAMP_HH_STATS_UK_01` (`STATS_DTTM`,`STATS_HH`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`USERID`,`ITL_TP_CODE`,`PROCESS_RESULT_CODE`),
  KEY `MOB_PROCESS_RESULT_ADSITE_CAMP_HH_STATS_IDX_02` (`ADVRTS_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_ADSITE_CAMP_HH_STATS_IDX_03` (`ITL_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_ADSITE_CAMP_HH_STATS_IDX_04` (`USERID`,`STATS_DTTM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='요청수 광고주별 시간대 통계 | 3개월'
 PARTITION BY RANGE (`STATS_DTTM`)
(PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_HH_STATS_202207` VALUES LESS THAN (20220801) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_HH_STATS_202208` VALUES LESS THAN (20220901) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_HH_STATS_202209` VALUES LESS THAN (20221001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_HH_STATS_202210` VALUES LESS THAN (20221101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_HH_STATS_202211` VALUES LESS THAN (20221201) ENGINE = InnoDB);


-- REQ_STATS.MOB_PROCESS_RESULT_ADSITE_CAMP_STATS definition

CREATE TABLE `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS` (
  `NO` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `STATS_DTTM` int(11) NOT NULL COMMENT '통계일자',
  `PLTFOM_TP_CODE` varchar(2) NOT NULL COMMENT '플랫폼구분코드|MOBON_COM_CODE.PLTFOM_TP_CODE',
  `ADVRTS_PRDT_CODE` varchar(2) NOT NULL COMMENT '광고상품코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE',
  `ADVRTS_TP_CODE` varchar(2) NOT NULL COMMENT '광고구분코드|MOBON_COM_CODE.ADVRTS_TP_CODE',
  `USERID` varchar(20) NOT NULL COMMENT '광고주아이디',
  `ITL_TP_CODE` varchar(2) NOT NULL COMMENT '연동구분코드|MOBON_COM_CODE.ITL_TP_CODE',
  `PROCESS_RESULT_CODE` varchar(2) NOT NULL COMMENT '처리유형|MOBON_COM_CODE.PROCESS_RESULT_CODE',
  `REQ_CNT` bigint(20) DEFAULT 0 COMMENT '송출요청횟수',
  `ASK_CNT` bigint(20) DEFAULT 0 COMMENT '광고요구횟수',
  `RES_CNT` bigint(20) DEFAULT 0 COMMENT '송출응답횟수',
  `ANS_SUCC_CNT` bigint(20) DEFAULT 0 COMMENT '광고응답성공횟수',
  `ANS_FAIL_CNT` bigint(20) DEFAULT 0 COMMENT '광고응답실패횟수',
  `REG_DTTM` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록시간',
  `ALT_DTTM` datetime DEFAULT NULL COMMENT '수정시간',
  PRIMARY KEY (`NO`,`STATS_DTTM`),
  UNIQUE KEY `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_UK_01` (`STATS_DTTM`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`USERID`,`ITL_TP_CODE`,`PROCESS_RESULT_CODE`),
  KEY `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_IDX_02` (`ADVRTS_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_IDX_03` (`ITL_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_IDX_04` (`USERID`,`STATS_DTTM`)
) ENGINE=InnoDB AUTO_INCREMENT=4943789 DEFAULT CHARSET=utf8 COMMENT='요청수 광고주별 일자별 통계 | 13개월'
 PARTITION BY RANGE (`STATS_DTTM`)
(PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_202109` VALUES LESS THAN (20211001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_202110` VALUES LESS THAN (20211101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_202111` VALUES LESS THAN (20211201) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_202112` VALUES LESS THAN (20220101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_202201` VALUES LESS THAN (20220201) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_202202` VALUES LESS THAN (20220301) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_202203` VALUES LESS THAN (20220401) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_202204` VALUES LESS THAN (20220501) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_202205` VALUES LESS THAN (20220601) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_202206` VALUES LESS THAN (20220701) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_202207` VALUES LESS THAN (20220801) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_202208` VALUES LESS THAN (20220901) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_202209` VALUES LESS THAN (20221001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_202210` VALUES LESS THAN (20221101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_ADSITE_CAMP_STATS_202211` VALUES LESS THAN (20221201) ENGINE = InnoDB);


-- REQ_STATS.MOB_PROCESS_RESULT_BROWSER_HH_STATS definition

CREATE TABLE `MOB_PROCESS_RESULT_BROWSER_HH_STATS` (
  `NO` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `STATS_DTTM` int(11) NOT NULL COMMENT '통계일자',
  `STATS_HH` varchar(2) NOT NULL COMMENT '통계일자',
  `PLTFOM_TP_CODE` varchar(2) NOT NULL COMMENT '플랫폼구분코드|MOBON_COM_CODE.PLTFORM_TP_CODE',
  `ADVRTS_PRDT_CODE` varchar(2) NOT NULL COMMENT '광고상품코드|MOBON_COM_CODE.ADVRTS_PRODT_CODE',
  `ADVRTS_TP_CODE` varchar(2) NOT NULL COMMENT '광고구분코드|MOBON_COM_CODE.ADVRTS_TP_CODE',
  `ITL_TP_CODE` varchar(2) NOT NULL COMMENT '연동구분코드|MOBON_COM_CODE.ITL_TP_CODE',
  `PROCESS_RESULT_CODE` varchar(2) NOT NULL COMMENT '처리유형|MOBON_COM_CODE.PROCESS_RESULT_CODE',
  `DEVICE_TP_CODE` varchar(2) NOT NULL COMMENT '사용자디바이스구분코드|MOBON_COM_CODE.DEVICE_TP_CODE',
  `BROWSER_TP_CODE` varchar(2) NOT NULL COMMENT '브라우저유형|MOBON_COM_CODE.BROWSER_TP_CODE',
  `REQ_CNT` int(11) DEFAULT 0 COMMENT '송출요청횟수',
  `ASK_CNT` int(11) DEFAULT 0 COMMENT '광고요구횟수',
  `RES_CNT` int(11) DEFAULT 0 COMMENT '송출응답횟수',
  `ANS_SUCC_CNT` int(11) DEFAULT 0 COMMENT '광고응답성공횟수',
  `ANS_FAIL_CNT` int(11) DEFAULT 0 COMMENT '광고응답실패횟수',
  `REG_DTTM` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록시간',
  `ALT_DTTM` datetime DEFAULT NULL COMMENT '수정시간',
  PRIMARY KEY (`NO`,`STATS_DTTM`),
  UNIQUE KEY `MOB_PROCESS_RESULT_BROWSER_HH_STATS_UK_01` (`STATS_DTTM`,`STATS_HH`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`ITL_TP_CODE`,`PROCESS_RESULT_CODE`,`DEVICE_TP_CODE`,`BROWSER_TP_CODE`),
  KEY `MOB_PROCESS_RESULT_BROWSER_HH_STATS_IDX_02` (`ADVRTS_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_BROWSER_HH_STATS_IDX_03` (`ITL_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_BROWSER_HH_STATS_IDX_04` (`BROWSER_TP_CODE`,`STATS_DTTM`)
) ENGINE=InnoDB AUTO_INCREMENT=130672820 DEFAULT CHARSET=utf8 COMMENT='요청수 브라우저 시간대 통계'
 PARTITION BY RANGE (`STATS_DTTM`)
(PARTITION `MOB_PROCESS_RESULT_BROWSER_HH_STATS_p20200601` VALUES LESS THAN (20200701) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_HH_STATS_p20220601` VALUES LESS THAN (20220701) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_HH_STATS_p20220701` VALUES LESS THAN (20220801) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_HH_STATS_p20220801` VALUES LESS THAN (20220901) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_HH_STATS_p20220901` VALUES LESS THAN (20221001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_HH_STATS_p20221001` VALUES LESS THAN (20221101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_HH_STATS_p20221101` VALUES LESS THAN (20221201) ENGINE = InnoDB);


-- REQ_STATS.MOB_PROCESS_RESULT_BROWSER_STATS definition

CREATE TABLE `MOB_PROCESS_RESULT_BROWSER_STATS` (
  `NO` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `STATS_DTTM` int(11) NOT NULL COMMENT '통계일자',
  `PLTFOM_TP_CODE` varchar(2) NOT NULL COMMENT '플랫폼구분코드|MOBON_COM_CODE.PLTFORM_TP_CODE',
  `ADVRTS_PRDT_CODE` varchar(2) NOT NULL COMMENT '광고상품코드|MOBON_COM_CODE.ADVRTS_PRODT_CODE',
  `ADVRTS_TP_CODE` varchar(2) NOT NULL COMMENT '광고구분코드|MOBON_COM_CODE.ADVRTS_TP_CODE',
  `ITL_TP_CODE` varchar(2) NOT NULL COMMENT '연동구분코드|MOBON_COM_CODE.ITL_TP_CODE',
  `PROCESS_RESULT_CODE` varchar(2) NOT NULL COMMENT '처리유형|MOBON_COM_CODE.PROCESS_RESULT_CODE',
  `DEVICE_TP_CODE` varchar(2) NOT NULL COMMENT '사용자디바이스구분코드|MOBON_COM_CODE.DEVICE_TP_CODE',
  `BROWSER_TP_CODE` varchar(2) NOT NULL COMMENT '브라우저유형|MOBON_COM_CODE.BROWSER_TP_CODE',
  `REQ_CNT` int(11) DEFAULT 0 COMMENT '송출요청횟수',
  `ASK_CNT` int(11) DEFAULT 0 COMMENT '광고요구횟수',
  `RES_CNT` int(11) DEFAULT 0 COMMENT '송출응답횟수',
  `ANS_SUCC_CNT` int(11) DEFAULT 0 COMMENT '광고응답성공횟수',
  `ANS_FAIL_CNT` int(11) DEFAULT 0 COMMENT '광고응답실패횟수',
  `REG_DTTM` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록시간',
  `ALT_DTTM` datetime DEFAULT NULL COMMENT '수정시간',
  PRIMARY KEY (`NO`,`STATS_DTTM`),
  UNIQUE KEY `STATS_DTTM` (`STATS_DTTM`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`ITL_TP_CODE`,`PROCESS_RESULT_CODE`,`DEVICE_TP_CODE`,`BROWSER_TP_CODE`),
  KEY `MOB_PROCESS_RESULT_BROWSER_STATS_IDX_02` (`ADVRTS_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_BROWSER_STATS_IDX_03` (`ITL_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_BROWSER_STATS_IDX_04` (`BROWSER_TP_CODE`,`STATS_DTTM`)
) ENGINE=InnoDB AUTO_INCREMENT=18402298 DEFAULT CHARSET=utf8 COMMENT='요청수 브라우저별 처리유형 통계'
 PARTITION BY RANGE (`STATS_DTTM`)
(PARTITION `MOB_PROCESS_RESULT_BROWSER_STATS_p20210901` VALUES LESS THAN (20211001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_STATS_p20211001` VALUES LESS THAN (20211101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_STATS_p20211101` VALUES LESS THAN (20211201) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_STATS_p20211201` VALUES LESS THAN (20220101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_STATS_p20220101` VALUES LESS THAN (20220201) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_STATS_p20220201` VALUES LESS THAN (20220301) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_STATS_p20220301` VALUES LESS THAN (20220401) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_STATS_p20220401` VALUES LESS THAN (20220501) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_STATS_p20220501` VALUES LESS THAN (20220601) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_STATS_p20220601` VALUES LESS THAN (20220701) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_STATS_p20220701` VALUES LESS THAN (20220801) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_STATS_p20220801` VALUES LESS THAN (20220901) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_STATS_p20220901` VALUES LESS THAN (20221001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_STATS_p20221001` VALUES LESS THAN (20221101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_BROWSER_STATS_p20221101` VALUES LESS THAN (20221201) ENGINE = InnoDB);


-- REQ_STATS.MOB_PROCESS_RESULT_CAMP_HH_STATS definition

CREATE TABLE `MOB_PROCESS_RESULT_CAMP_HH_STATS` (
  `NO` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `STATS_DTTM` int(11) NOT NULL COMMENT '통계일자',
  `STATS_HH` varchar(2) NOT NULL COMMENT '통계일자',
  `PLTFOM_TP_CODE` varchar(2) NOT NULL COMMENT '플랫폼구분코드|MOBON_COM_CODE.PLTFOM_TP_CODE',
  `ADVRTS_PRDT_CODE` varchar(2) NOT NULL COMMENT '광고상품코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE',
  `ADVRTS_TP_CODE` varchar(2) NOT NULL COMMENT '광고구분코드|MOBON_COM_CODE.ADVRTS_TP_CODE',
  `SITE_CODE` varchar(40) NOT NULL COMMENT '지면번호',
  `ITL_TP_CODE` varchar(2) NOT NULL COMMENT '연동구분코드|MOBON_COM_CODE.ITL_TP_CODE',
  `PROCESS_RESULT_CODE` varchar(2) NOT NULL COMMENT '처리유형|MOBON_COM_CODE.PROCESS_RESULT_CODE',
  `REQ_CNT` int(11) DEFAULT 0 COMMENT '송출요청횟수',
  `ASK_CNT` int(11) DEFAULT 0 COMMENT '광고요구횟수',
  `RES_CNT` int(11) DEFAULT 0 COMMENT '송출응답횟수',
  `ANS_SUCC_CNT` int(11) DEFAULT 0 COMMENT '광고응답성공횟수',
  `ANS_FAIL_CNT` int(11) DEFAULT 0 COMMENT '광고응답실패횟수',
  `REG_DTTM` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록시간',
  `ALT_DTTM` datetime DEFAULT NULL COMMENT '수정시간',
  PRIMARY KEY (`NO`,`STATS_DTTM`),
  UNIQUE KEY `MOB_PROCESS_RESULT_CAMP_HH_STATS_UK_01` (`STATS_DTTM`,`STATS_HH`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`SITE_CODE`,`ITL_TP_CODE`,`PROCESS_RESULT_CODE`),
  KEY `MOB_PROCESS_RESULT_CAMP_HH_STATS_IDX_02` (`ADVRTS_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_CAMP_HH_STATS_IDX_03` (`ITL_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_CAMP_HH_STATS_IDX_04` (`SITE_CODE`,`STATS_DTTM`)
) ENGINE=InnoDB AUTO_INCREMENT=403107572055 DEFAULT CHARSET=utf8 COMMENT='요청수 캠패인 시간대 통계'
 PARTITION BY RANGE (`STATS_DTTM`)
(PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220902` VALUES LESS THAN (20220903) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220903` VALUES LESS THAN (20220904) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220904` VALUES LESS THAN (20220905) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220905` VALUES LESS THAN (20220906) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220906` VALUES LESS THAN (20220907) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220907` VALUES LESS THAN (20220908) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220908` VALUES LESS THAN (20220909) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220909` VALUES LESS THAN (20220910) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220910` VALUES LESS THAN (20220911) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220911` VALUES LESS THAN (20220912) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220912` VALUES LESS THAN (20220913) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220913` VALUES LESS THAN (20220914) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220914` VALUES LESS THAN (20220915) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220915` VALUES LESS THAN (20220916) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220916` VALUES LESS THAN (20220917) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220917` VALUES LESS THAN (20220918) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220918` VALUES LESS THAN (20220919) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220919` VALUES LESS THAN (20220920) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220920` VALUES LESS THAN (20220921) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220921` VALUES LESS THAN (20220922) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220922` VALUES LESS THAN (20220923) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220923` VALUES LESS THAN (20220924) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220924` VALUES LESS THAN (20220925) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220925` VALUES LESS THAN (20220926) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220926` VALUES LESS THAN (20220927) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220927` VALUES LESS THAN (20220928) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220928` VALUES LESS THAN (20220929) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220929` VALUES LESS THAN (20220930) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20220930` VALUES LESS THAN (20221001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221001` VALUES LESS THAN (20221002) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221002` VALUES LESS THAN (20221003) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221003` VALUES LESS THAN (20221004) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221004` VALUES LESS THAN (20221005) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221005` VALUES LESS THAN (20221006) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221006` VALUES LESS THAN (20221007) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221007` VALUES LESS THAN (20221008) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221008` VALUES LESS THAN (20221009) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221009` VALUES LESS THAN (20221010) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221010` VALUES LESS THAN (20221011) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221011` VALUES LESS THAN (20221012) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221012` VALUES LESS THAN (20221013) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221013` VALUES LESS THAN (20221014) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221014` VALUES LESS THAN (20221015) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221015` VALUES LESS THAN (20221016) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221016` VALUES LESS THAN (20221017) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221017` VALUES LESS THAN (20221018) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221018` VALUES LESS THAN (20221019) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221019` VALUES LESS THAN (20221020) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221020` VALUES LESS THAN (20221021) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221021` VALUES LESS THAN (20221022) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_HH_STATS_20221022` VALUES LESS THAN (20221023) ENGINE = InnoDB);


-- REQ_STATS.MOB_PROCESS_RESULT_CAMP_STATS definition

CREATE TABLE `MOB_PROCESS_RESULT_CAMP_STATS` (
  `NO` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `STATS_DTTM` int(11) NOT NULL COMMENT '통계일자',
  `PLTFOM_TP_CODE` varchar(2) NOT NULL COMMENT '플랫폼구분코드|MOBON_COM_CODE.PLTFOM_TP_CODE',
  `ADVRTS_PRDT_CODE` varchar(2) NOT NULL COMMENT '광고상품코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE',
  `ADVRTS_TP_CODE` varchar(2) NOT NULL COMMENT '광고구분코드|MOBON_COM_CODE.ADVRTS_TP_CODE',
  `SITE_CODE` varchar(40) NOT NULL COMMENT '지면번호',
  `ITL_TP_CODE` varchar(2) NOT NULL COMMENT '연동구분코드|MOBON_COM_CODE.ITL_TP_CODE',
  `PROCESS_RESULT_CODE` varchar(2) NOT NULL COMMENT '처리유형|MOBON_COM_CODE.PROCESS_RESULT_CODE',
  `REQ_CNT` int(11) DEFAULT 0 COMMENT '송출요청횟수',
  `ASK_CNT` int(11) DEFAULT 0 COMMENT '광고요구횟수',
  `RES_CNT` int(11) DEFAULT 0 COMMENT '송출응답횟수',
  `ANS_SUCC_CNT` int(11) DEFAULT 0 COMMENT '광고응답성공횟수',
  `ANS_FAIL_CNT` int(11) DEFAULT 0 COMMENT '광고응답실패횟수',
  `REG_DTTM` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록시간',
  `ALT_DTTM` datetime DEFAULT NULL COMMENT '수정시간',
  PRIMARY KEY (`NO`,`STATS_DTTM`),
  UNIQUE KEY `MOB_PROCESS_RESULT_CAMP_STATS_UK_01` (`STATS_DTTM`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`SITE_CODE`,`ITL_TP_CODE`,`PROCESS_RESULT_CODE`),
  KEY `MOB_PROCESS_RESULT_CAMP_STATS_IDX_02` (`ADVRTS_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_CAMP_STATS_IDX_03` (`ITL_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_CAMP_STATS_IDX_04` (`SITE_CODE`,`STATS_DTTM`)
) ENGINE=InnoDB AUTO_INCREMENT=401333536489 DEFAULT CHARSET=utf8 COMMENT='요청수 캠패인 통계'
 PARTITION BY RANGE (`STATS_DTTM`)
(PARTITION `MOB_PROCESS_RESULT_CAMP_STATS_p20210901` VALUES LESS THAN (20211001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_STATS_p20211001` VALUES LESS THAN (20211101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_STATS_p20211101` VALUES LESS THAN (20211201) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_STATS_p20211201` VALUES LESS THAN (20220101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_STATS_p20220101` VALUES LESS THAN (20220201) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_STATS_p20220201` VALUES LESS THAN (20220301) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_STATS_p20220301` VALUES LESS THAN (20220401) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_STATS_p20220401` VALUES LESS THAN (20220501) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_STATS_p20220501` VALUES LESS THAN (20220601) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_STATS_p20220601` VALUES LESS THAN (20220701) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_STATS_p20220701` VALUES LESS THAN (20220801) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_STATS_p20220801` VALUES LESS THAN (20220901) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_STATS_p20220901` VALUES LESS THAN (20221001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_STATS_p20221001` VALUES LESS THAN (20221101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_CAMP_STATS_p20221101` VALUES LESS THAN (20221201) ENGINE = InnoDB);


-- REQ_STATS.MOB_PROCESS_RESULT_EXL_HH_STATS definition

CREATE TABLE `MOB_PROCESS_RESULT_EXL_HH_STATS` (
  `NO` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `STATS_DTTM` int(11) NOT NULL COMMENT '통계일자',
  `STATS_HH` varchar(2) NOT NULL COMMENT '통계일자',
  `PLTFOM_TP_CODE` varchar(2) NOT NULL COMMENT '플랫폼구분코드|MOBON_COM_CODE.PLTFORM_TP_CODE',
  `ADVRTS_PRDT_CODE` varchar(2) NOT NULL COMMENT '광고상품코드|MOBON_COM_CODE.ADVRTS_PRODT_CODE',
  `ADVRTS_TP_CODE` varchar(2) NOT NULL COMMENT '광고구분코드|MOBON_COM_CODE.ADVRTS_TP_CODE',
  `MEDIA_SCRIPT_NO` int(11) DEFAULT NULL COMMENT '지면번호',
  `AD_EXL_TP_CODE` varchar(2) NOT NULL COMMENT '외부연동사코드',
  `EXL_ITL_SEQ` bigint(20) unsigned NOT NULL COMMENT '외부연동순서|외부 연동 순서|EXL_ITL_INFO.EXL_ITL_SEQ|',
  `ITL_TP_CODE` varchar(2) NOT NULL COMMENT '연동구분코드|MOBON_COM_CODE.ITL_TP_CODE',
  `PROCESS_RESULT_CODE` varchar(2) NOT NULL COMMENT '처리유형|MOBON_COM_CODE.PROCESS_RESULT_CODE',
  `REQ_CNT` int(11) DEFAULT 0 COMMENT '송출요청횟수',
  `ASK_CNT` int(11) DEFAULT 0 COMMENT '광고요구횟수',
  `RES_CNT` int(11) DEFAULT 0 COMMENT '송출응답횟수',
  `ANS_SUCC_CNT` int(11) DEFAULT 0 COMMENT '광고응답성공횟수',
  `ANS_FAIL_CNT` int(11) DEFAULT 0 COMMENT '광고응답실패횟수',
  `REG_DTTM` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록시간',
  `ALT_DTTM` datetime DEFAULT NULL COMMENT '수정시간',
  PRIMARY KEY (`NO`,`STATS_DTTM`),
  UNIQUE KEY `MOB_PROCESS_RESULT_EXL_HH_STATS_UK_01` (`STATS_DTTM`,`STATS_HH`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`MEDIA_SCRIPT_NO`,`AD_EXL_TP_CODE`,`EXL_ITL_SEQ`,`ITL_TP_CODE`,`PROCESS_RESULT_CODE`),
  KEY `MOB_PROCESS_RESULT_EXL_HH_STATS_IDX_02` (`ADVRTS_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_EXL_HH_STATS_IDX_03` (`ITL_TP_CODE`,`STATS_DTTM`)
) ENGINE=InnoDB AUTO_INCREMENT=401032591 DEFAULT CHARSET=utf8 COMMENT='요청수 외부연동 시간대 통계'
 PARTITION BY RANGE (`STATS_DTTM`)
(PARTITION `MOB_PROCESS_RESULT_EXL_HH_STATS_p20220601` VALUES LESS THAN (20220701) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_HH_STATS_p20220701` VALUES LESS THAN (20220801) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_HH_STATS_p20220801` VALUES LESS THAN (20220901) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_HH_STATS_p20220901` VALUES LESS THAN (20221001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_HH_STATS_p20221001` VALUES LESS THAN (20221101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_HH_STATS_p20221101` VALUES LESS THAN (20221201) ENGINE = InnoDB);


-- REQ_STATS.MOB_PROCESS_RESULT_EXL_STATS definition

CREATE TABLE `MOB_PROCESS_RESULT_EXL_STATS` (
  `NO` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `STATS_DTTM` int(11) NOT NULL COMMENT '통계일자',
  `PLTFOM_TP_CODE` varchar(2) NOT NULL COMMENT '플랫폼구분코드|MOBON_COM_CODE.PLTFORM_TP_CODE',
  `ADVRTS_PRDT_CODE` varchar(2) NOT NULL COMMENT '광고상품코드|MOBON_COM_CODE.ADVRTS_PRODT_CODE',
  `ADVRTS_TP_CODE` varchar(2) NOT NULL COMMENT '광고구분코드|MOBON_COM_CODE.ADVRTS_TP_CODE',
  `MEDIA_SCRIPT_NO` int(11) DEFAULT NULL COMMENT '지면번호',
  `AD_EXL_TP_CODE` varchar(2) DEFAULT '',
  `EXL_ITL_SEQ` bigint(20) unsigned NOT NULL COMMENT '외부연동순서|외부 연동 순서|EXL_ITL_INFO.EXL_ITL_SEQ|',
  `ITL_TP_CODE` varchar(2) NOT NULL COMMENT '연동구분코드|MOBON_COM_CODE.ITL_TP_CODE',
  `PROCESS_RESULT_CODE` varchar(2) NOT NULL COMMENT '처리유형|MOBON_COM_CODE.PROCESS_RESULT_CODE',
  `REQ_CNT` int(11) DEFAULT 0 COMMENT '송출요청횟수',
  `ASK_CNT` int(11) DEFAULT 0 COMMENT '광고요구횟수',
  `RES_CNT` int(11) DEFAULT 0 COMMENT '송출응답횟수',
  `ANS_SUCC_CNT` int(11) DEFAULT 0 COMMENT '광고응답성공횟수',
  `ANS_FAIL_CNT` int(11) DEFAULT 0 COMMENT '광고응답실패횟수',
  `REG_DTTM` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록시간',
  `ALT_DTTM` datetime DEFAULT NULL COMMENT '수정시간',
  PRIMARY KEY (`NO`,`STATS_DTTM`),
  UNIQUE KEY `MOB_PROCESS_RESULT_EXL_STATS_UK_01` (`STATS_DTTM`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`MEDIA_SCRIPT_NO`,`AD_EXL_TP_CODE`,`EXL_ITL_SEQ`,`ITL_TP_CODE`,`PROCESS_RESULT_CODE`),
  KEY `MOB_PROCESS_RESULT_EXL_STATS_IDX_02` (`ADVRTS_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_EXL_STATS_IDX_03` (`ITL_TP_CODE`,`STATS_DTTM`)
) ENGINE=InnoDB AUTO_INCREMENT=41059331 DEFAULT CHARSET=utf8 COMMENT='요청수 일자별 통계'
 PARTITION BY RANGE (`STATS_DTTM`)
(PARTITION `MOB_PROCESS_RESULT_EXL_STATS_p20210901` VALUES LESS THAN (20211001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_STATS_p20211001` VALUES LESS THAN (20211101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_STATS_p20211101` VALUES LESS THAN (20211201) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_STATS_p20211201` VALUES LESS THAN (20220101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_STATS_p20220101` VALUES LESS THAN (20220201) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_STATS_p20220201` VALUES LESS THAN (20220301) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_STATS_p20220301` VALUES LESS THAN (20220401) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_STATS_p20220401` VALUES LESS THAN (20220501) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_STATS_p20220501` VALUES LESS THAN (20220601) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_STATS_p20220601` VALUES LESS THAN (20220701) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_STATS_p20220701` VALUES LESS THAN (20220801) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_STATS_p20220801` VALUES LESS THAN (20220901) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_STATS_p20220901` VALUES LESS THAN (20221001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_STATS_p20221001` VALUES LESS THAN (20221101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_EXL_STATS_p20221101` VALUES LESS THAN (20221201) ENGINE = InnoDB);


-- REQ_STATS.MOB_PROCESS_RESULT_MEDIA_SCRIPT_HH_STATS definition

CREATE TABLE `MOB_PROCESS_RESULT_MEDIA_SCRIPT_HH_STATS` (
  `NO` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `STATS_DTTM` int(11) NOT NULL COMMENT '통계일자',
  `STATS_HH` varchar(2) NOT NULL COMMENT '통계일자',
  `PLTFOM_TP_CODE` varchar(2) NOT NULL COMMENT '플랫폼구분코드|MOBON_COM_CODE.PLTFOM_TP_CODE',
  `ADVRTS_PRDT_CODE` varchar(2) NOT NULL COMMENT '광고상품코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE',
  `ADVRTS_TP_CODE` varchar(2) NOT NULL COMMENT '광고구분코드|MOBON_COM_CODE.ADVRTS_TP_CODE',
  `MEDIA_SCRIPT_NO` int(11) NOT NULL COMMENT '지면번호',
  `ITL_TP_CODE` varchar(2) NOT NULL COMMENT '연동구분코드|MOBON_COM_CODE.ITL_TP_CODE',
  `PROCESS_RESULT_CODE` varchar(2) NOT NULL COMMENT '처리유형|MOBON_COM_CODE.PROCESS_RESULT_CODE',
  `MEDIA_TP_CODE` varchar(2) DEFAULT NULL COMMENT '매체구분코드|MOBON_COM_CODE.MEDIA_TP_CODE',
  `MEDIA_ID` varchar(30) DEFAULT NULL COMMENT '매체아이디',
  `ADUT_PRO_TP_CODE` varchar(2) DEFAULT NULL COMMENT '매체수익보장/비보장|MOBON_COM_CODE.ADUT_PRO_TP_CODE',
  `ADUT_FORM_TP_CODE` varchar(2) DEFAULT NULL COMMENT '매체과금유형|MOBON_COM_CODE.ADUT_FORM_TP_CODE',
  `REQ_CNT` int(11) DEFAULT 0 COMMENT '송출요청횟수',
  `ASK_CNT` int(11) DEFAULT 0 COMMENT '광고요구횟수',
  `RES_CNT` int(11) DEFAULT 0 COMMENT '송출응답횟수',
  `ANS_SUCC_CNT` int(11) DEFAULT 0 COMMENT '광고응답성공횟수',
  `ANS_FAIL_CNT` int(11) DEFAULT 0 COMMENT '광고응답실패횟수',
  `REG_DTTM` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록시간',
  `ALT_DTTM` datetime DEFAULT NULL COMMENT '수정시간',
  PRIMARY KEY (`NO`,`STATS_DTTM`),
  UNIQUE KEY `MOB_PROCESS_RESULT_MEDIA_SCRIPT_HH_STATS_UK_01` (`STATS_DTTM`,`STATS_HH`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`MEDIA_SCRIPT_NO`,`ITL_TP_CODE`,`PROCESS_RESULT_CODE`),
  KEY `MOB_PROCESS_RESULT_MEDIA_SCRIPT_HH_STATS_IDX_02` (`ADVRTS_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_MEDIA_SCRIPT_HH_STATS_IDX_03` (`ITL_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_MEDIA_SCRIPT_HH_STATS_IDX_04` (`MEDIA_SCRIPT_NO`,`STATS_DTTM`)
) ENGINE=InnoDB AUTO_INCREMENT=2456820469 DEFAULT CHARSET=utf8 COMMENT='요청수 지면 시간대 통계'
 PARTITION BY RANGE (`STATS_DTTM`)
(PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_HH_STATS_p20220601` VALUES LESS THAN (20220701) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_HH_STATS_p20220701` VALUES LESS THAN (20220801) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_HH_STATS_p20220801` VALUES LESS THAN (20220901) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_HH_STATS_p20220901` VALUES LESS THAN (20221001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_HH_STATS_p20221001` VALUES LESS THAN (20221101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_HH_STATS_p20221101` VALUES LESS THAN (20221201) ENGINE = InnoDB);


-- REQ_STATS.MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS definition

CREATE TABLE `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS` (
  `NO` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `STATS_DTTM` int(11) NOT NULL COMMENT '통계일자',
  `PLTFOM_TP_CODE` varchar(2) NOT NULL COMMENT '플랫폼구분코드|MOBON_COM_CODE.PLTFOM_TP_CODE',
  `ADVRTS_PRDT_CODE` varchar(2) NOT NULL COMMENT '광고상품코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE',
  `ADVRTS_TP_CODE` varchar(2) NOT NULL COMMENT '광고구분코드|MOBON_COM_CODE.ADVRTS_TP_CODE',
  `MEDIA_SCRIPT_NO` int(11) NOT NULL COMMENT '지면번호',
  `ITL_TP_CODE` varchar(2) NOT NULL COMMENT '연동구분코드|MOBON_COM_CODE.ITL_TP_CODE',
  `PROCESS_RESULT_CODE` varchar(2) NOT NULL COMMENT '처리유형|MOBON_COM_CODE.PROCESS_RESULT_CODE',
  `MEDIA_TP_CODE` varchar(2) DEFAULT NULL COMMENT '매체구분코드|MOBON_COM_CODE.MEDIA_TP_CODE',
  `MEDIA_ID` varchar(30) DEFAULT NULL COMMENT '매체아이디',
  `ADUT_PRO_TP_CODE` varchar(2) DEFAULT NULL COMMENT '매체수익보장/비보장|MOBON_COM_CODE.ADUT_PRO_TP_CODE',
  `ADUT_FORM_TP_CODE` varchar(2) DEFAULT NULL COMMENT '매체과금유형|MOBON_COM_CODE.ADUT_FORM_TP_CODE',
  `REQ_CNT` int(11) DEFAULT 0 COMMENT '송출요청횟수',
  `ASK_CNT` int(11) DEFAULT 0 COMMENT '광고요구횟수',
  `RES_CNT` int(11) DEFAULT 0 COMMENT '송출응답횟수',
  `ANS_SUCC_CNT` int(11) DEFAULT 0 COMMENT '광고응답성공횟수',
  `ANS_FAIL_CNT` int(11) DEFAULT 0 COMMENT '광고응답실패횟수',
  `REG_DTTM` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록시간',
  `ALT_DTTM` datetime DEFAULT NULL COMMENT '수정시간',
  PRIMARY KEY (`NO`,`STATS_DTTM`),
  UNIQUE KEY `STATS_DTTM` (`STATS_DTTM`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`MEDIA_SCRIPT_NO`,`ITL_TP_CODE`,`PROCESS_RESULT_CODE`),
  KEY `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_IDX_02` (`ADVRTS_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_IDX_03` (`ITL_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_IDX_04` (`MEDIA_SCRIPT_NO`,`STATS_DTTM`)
) ENGINE=InnoDB AUTO_INCREMENT=455240271 DEFAULT CHARSET=utf8 COMMENT='요청수 일자별 지면별 통계'
 PARTITION BY RANGE (`STATS_DTTM`)
(PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_p20210901` VALUES LESS THAN (20211001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_p20211001` VALUES LESS THAN (20211101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_p20211101` VALUES LESS THAN (20211201) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_p20211201` VALUES LESS THAN (20220101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_p20220101` VALUES LESS THAN (20220201) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_p20220201` VALUES LESS THAN (20220301) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_p20220301` VALUES LESS THAN (20220401) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_p20220401` VALUES LESS THAN (20220501) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_p20220501` VALUES LESS THAN (20220601) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_p20220601` VALUES LESS THAN (20220701) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_p20220701` VALUES LESS THAN (20220801) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_p20220801` VALUES LESS THAN (20220901) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_p20220901` VALUES LESS THAN (20221001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_p20221001` VALUES LESS THAN (20221101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_MEDIA_SCRIPT_STATS_p20221101` VALUES LESS THAN (20221201) ENGINE = InnoDB);


-- REQ_STATS.MOB_PROCESS_RESULT_OS_HH_STATS definition

CREATE TABLE `MOB_PROCESS_RESULT_OS_HH_STATS` (
  `NO` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `STATS_DTTM` int(11) NOT NULL COMMENT '통계일자',
  `STATS_HH` varchar(2) NOT NULL COMMENT '통계일자',
  `PLTFOM_TP_CODE` varchar(2) NOT NULL COMMENT '플랫폼구분코드|MOBON_COM_CODE.PLTFOM_TP_CODE',
  `ADVRTS_PRDT_CODE` varchar(2) NOT NULL COMMENT '광고상품코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE',
  `ADVRTS_TP_CODE` varchar(2) NOT NULL COMMENT '광고구분코드|MOBON_COM_CODE.ADVRTS_TP_CODE',
  `ITL_TP_CODE` varchar(2) NOT NULL COMMENT '연동구분코드|MOBON_COM_CODE.ITL_TP_CODE',
  `PROCESS_RESULT_CODE` varchar(2) NOT NULL COMMENT '처리유형|MOBON_COM_CODE.PROCESS_RESULT_CODE',
  `DEVICE_TP_CODE` varchar(2) NOT NULL COMMENT '사용자디바이스구분코드|MOBON_COM_CODE.DEVICE_TP_CODE',
  `OS_TP_CODE` varchar(2) NOT NULL COMMENT '운영체제유형|MOBON_COM_CODE.OS_TP_CODE',
  `REQ_CNT` int(11) DEFAULT 0 COMMENT '송출요청횟수',
  `ASK_CNT` int(11) DEFAULT 0 COMMENT '광고요구횟수',
  `RES_CNT` int(11) DEFAULT 0 COMMENT '송출응답횟수',
  `ANS_SUCC_CNT` int(11) DEFAULT 0 COMMENT '광고응답성공횟수',
  `ANS_FAIL_CNT` int(11) DEFAULT 0 COMMENT '광고응답실패횟수',
  `REG_DTTM` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록시간',
  `ALT_DTTM` datetime DEFAULT NULL COMMENT '수정시간',
  PRIMARY KEY (`NO`,`STATS_DTTM`),
  UNIQUE KEY `MOB_PROCESS_RESULT_OS_HH_STATS_UK_01` (`STATS_DTTM`,`STATS_HH`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`ITL_TP_CODE`,`PROCESS_RESULT_CODE`,`DEVICE_TP_CODE`,`OS_TP_CODE`),
  KEY `MOB_PROCESS_RESULT_OS_HH_STATS_IDX_02` (`ADVRTS_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_OS_HH_STATS_IDX_03` (`ITL_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_OS_HH_STATS_IDX_04` (`OS_TP_CODE`,`STATS_DTTM`)
) ENGINE=InnoDB AUTO_INCREMENT=57115810 DEFAULT CHARSET=utf8 COMMENT='요청수 브라우저 시간대 통계'
 PARTITION BY RANGE (`STATS_DTTM`)
(PARTITION `MOB_PROCESS_RESULT_OS_HH_STATS_p20220601` VALUES LESS THAN (20220701) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_HH_STATS_p20220701` VALUES LESS THAN (20220801) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_HH_STATS_p20220801` VALUES LESS THAN (20220901) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_HH_STATS_p20220901` VALUES LESS THAN (20221001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_HH_STATS_p20221001` VALUES LESS THAN (20221101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_HH_STATS_p20221101` VALUES LESS THAN (20221201) ENGINE = InnoDB);


-- REQ_STATS.MOB_PROCESS_RESULT_OS_STATS definition

CREATE TABLE `MOB_PROCESS_RESULT_OS_STATS` (
  `NO` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `STATS_DTTM` int(11) NOT NULL COMMENT '통계일자',
  `PLTFOM_TP_CODE` varchar(2) NOT NULL COMMENT '플랫폼구분코드|MOBON_COM_CODE.PLTFOM_TP_CODE',
  `ADVRTS_PRDT_CODE` varchar(2) NOT NULL COMMENT '광고상품코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE',
  `ADVRTS_TP_CODE` varchar(2) NOT NULL COMMENT '광고구분코드|MOBON_COM_CODE.ADVRTS_TP_CODE',
  `ITL_TP_CODE` varchar(2) NOT NULL COMMENT '연동구분코드|MOBON_COM_CODE.ITL_TP_CODE',
  `PROCESS_RESULT_CODE` varchar(2) NOT NULL COMMENT '처리유형|MOBON_COM_CODE.PROCESS_RESULT_CODE',
  `DEVICE_TP_CODE` varchar(2) NOT NULL COMMENT '사용자디바이스구분코드|MOBON_COM_CODE.DEVICE_TP_CODE',
  `OS_TP_CODE` varchar(2) NOT NULL COMMENT '운영체제유형|MOBON_COM_CODE.OS_TP_CODE',
  `REQ_CNT` int(11) DEFAULT 0 COMMENT '송출요청횟수',
  `ASK_CNT` int(11) DEFAULT 0 COMMENT '광고요구횟수',
  `RES_CNT` int(11) DEFAULT 0 COMMENT '송출응답횟수',
  `ANS_SUCC_CNT` int(11) DEFAULT 0 COMMENT '광고응답성공횟수',
  `ANS_FAIL_CNT` int(11) DEFAULT 0 COMMENT '광고응답실패횟수',
  `REG_DTTM` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록시간',
  `ALT_DTTM` datetime DEFAULT NULL COMMENT '수정시간',
  PRIMARY KEY (`NO`,`STATS_DTTM`),
  UNIQUE KEY `STATS_DTTM` (`STATS_DTTM`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`ITL_TP_CODE`,`PROCESS_RESULT_CODE`,`DEVICE_TP_CODE`,`OS_TP_CODE`),
  KEY `MOB_PROCESS_RESULT_OS_STATS_IDX_02` (`ADVRTS_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_OS_STATS_IDX_03` (`ITL_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_RESULT_OS_STATS_IDX_04` (`OS_TP_CODE`,`STATS_DTTM`)
) ENGINE=InnoDB AUTO_INCREMENT=9760405 DEFAULT CHARSET=utf8 COMMENT='요청수 브라우저별 처리유형 통계'
 PARTITION BY RANGE (`STATS_DTTM`)
(PARTITION `MOB_PROCESS_RESULT_OS_STATS_p20210901` VALUES LESS THAN (20211001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_STATS_p20211001` VALUES LESS THAN (20211101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_STATS_p20211101` VALUES LESS THAN (20211201) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_STATS_p20211201` VALUES LESS THAN (20220101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_STATS_p20220101` VALUES LESS THAN (20220201) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_STATS_p20220201` VALUES LESS THAN (20220301) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_STATS_p20220301` VALUES LESS THAN (20220401) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_STATS_p20220401` VALUES LESS THAN (20220501) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_STATS_p20220501` VALUES LESS THAN (20220601) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_STATS_p20220601` VALUES LESS THAN (20220701) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_STATS_p20220701` VALUES LESS THAN (20220801) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_STATS_p20220801` VALUES LESS THAN (20220901) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_STATS_p20220901` VALUES LESS THAN (20221001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_STATS_p20221001` VALUES LESS THAN (20221101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_RESULT_OS_STATS_p20221101` VALUES LESS THAN (20221201) ENGINE = InnoDB);


-- REQ_STATS.MOB_PROCESS_STATS definition

CREATE TABLE `MOB_PROCESS_STATS` (
  `NO` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `STATS_DTTM` int(11) NOT NULL COMMENT '통계일자',
  `PLTFOM_TP_CODE` varchar(2) NOT NULL COMMENT '플랫폼구분코드|MOBON_COM_CODE.PLTFOM_TP_CODE',
  `ADVRTS_PRDT_CODE` varchar(2) NOT NULL COMMENT '광고상품코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE',
  `ADVRTS_TP_CODE` varchar(2) NOT NULL COMMENT '광고구분코드|MOBON_COM_CODE.ADVRTS_TP_CODE',
  `ITL_TP_CODE` varchar(2) NOT NULL COMMENT '연동구분코드|MOBON_COM_CODE.ITL_TP_CODE',
  `REQ_CNT` bigint(20) unsigned DEFAULT 0 COMMENT '송출요청횟수',
  `ASK_CNT` bigint(20) unsigned DEFAULT 0 COMMENT '광고요구횟수',
  `RES_CNT` bigint(20) unsigned DEFAULT 0 COMMENT '송출응답횟수',
  `ANS_SUCC_CNT` bigint(20) unsigned DEFAULT 0 COMMENT '광고응답성공횟수',
  `ANS_FAIL_CNT` bigint(20) unsigned DEFAULT 0 COMMENT '광고응답실패횟수',
  `REG_DTTM` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록시간',
  `ALT_DTTM` datetime DEFAULT NULL COMMENT '수정시간',
  PRIMARY KEY (`NO`,`STATS_DTTM`),
  UNIQUE KEY `STATS_DTTM` (`STATS_DTTM`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`ITL_TP_CODE`),
  KEY `MOB_PROCESS_STATS_IDX_02` (`ADVRTS_TP_CODE`,`STATS_DTTM`),
  KEY `MOB_PROCESS_STATS_IDX_03` (`ITL_TP_CODE`,`STATS_DTTM`)
) ENGINE=InnoDB AUTO_INCREMENT=670041 DEFAULT CHARSET=utf8 COMMENT='요청수 일자별 통계'
 PARTITION BY RANGE (`STATS_DTTM`)
(PARTITION `MOB_PROCESS_STATS_p20210901` VALUES LESS THAN (20211001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_STATS_p20211001` VALUES LESS THAN (20211101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_STATS_p20211101` VALUES LESS THAN (20211201) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_STATS_p20211201` VALUES LESS THAN (20220101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_STATS_p20220101` VALUES LESS THAN (20220201) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_STATS_p20220201` VALUES LESS THAN (20220301) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_STATS_p20220301` VALUES LESS THAN (20220401) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_STATS_p20220401` VALUES LESS THAN (20220501) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_STATS_p20220501` VALUES LESS THAN (20220601) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_STATS_p20220601` VALUES LESS THAN (20220701) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_STATS_p20220701` VALUES LESS THAN (20220801) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_STATS_p20220801` VALUES LESS THAN (20220901) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_STATS_p20220901` VALUES LESS THAN (20221001) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_STATS_p20221001` VALUES LESS THAN (20221101) ENGINE = InnoDB,
 PARTITION `MOB_PROCESS_STATS_p20221101` VALUES LESS THAN (20221201) ENGINE = InnoDB);