DELIMITER $$

DROP PROCEDURE IF EXISTS `sp_conv_step2`$$

CREATE PROCEDURE `sp_conv_step2`(
  $ACTION_NO VARCHAR(100) CHARACTER SET euckr
  , $PARTDT INT
  , $IP VARCHAR(20) CHARACTER SET euckr
  , $ORDCODE VARCHAR(100) CHARACTER SET euckr
  , $ORDRFURL VARCHAR(200) CHARACTER SET euckr
  , $ORDPCODE VARCHAR(100) CHARACTER SET euckr
  , $ORDQTY INT
  , $ORDPRICE INT
  , $USERID VARCHAR(20) CHARACTER SET euckr
  , $MEDIA_ID VARCHAR(13) CHARACTER SET euckr
  , $MEDIA_CODE VARCHAR(13) CHARACTER SET euckr
  , $SITECODE VARCHAR(32) CHARACTER SET euckr
  , $PLATFORM VARCHAR(2) CHARACTER SET euckr
  , $ADGUBUN VARCHAR(2) CHARACTER SET euckr
  , $ADPRODUCT VARCHAR(5) CHARACTER SET euckr
  , $ACTGUBUN VARCHAR(10) CHARACTER SET euckr
  , $MCGB VARCHAR(100) CHARACTER SET euckr
  , $PNM VARCHAR(200) CHARACTER SET euckr
  , $UNAME VARCHAR(200) CHARACTER SET euckr
  , $USEX CHAR(1) CHARACTER SET euckr
  , $UPNO VARCHAR(20) CHARACTER SET euckr
  , $IN_HOUR VARCHAR(20) CHARACTER SET euckr
  , $DIRECT VARCHAR(5) CHARACTER SET euckr
  , $REGDATE TIMESTAMP
  , $shopcon_sereal_no INT(11)
  , $shopcon_weight INT(11)
  , $LAST_CLICK_TIME VARCHAR(14) CHARACTER SET euckr
  , $MOBON_YN VARCHAR(1) CHARACTER SET euckr
  , $INFLOW_ROUTE VARCHAR(4000) CHARACTER SET euckr
  , $EXL_ITL_YN VARCHAR(1)
  )
BEGIN
	DECLARE $TRGT_ORDER_AMT INT;
	DECLARE $TRGT_ORDER_CNT INT;
	DECLARE $TRGT_ORDER_QY INT;
	        
	DECLARE $actgb VARCHAR(10);
	DECLARE $SESION_SELNG_YN VARCHAR(1);
	DECLARE $DIRECT_YN VARCHAR(1);
	SET $actgb = $ACTGUBUN;

	IF $ADPRODUCT='ico' THEN 
		SET $actgb='C';
	END IF ;
	
	IF $IN_HOUR <=24 THEN
		SET $SESION_SELNG_YN = 'Y';
	ELSE
		SET $SESION_SELNG_YN = 'N';
	END IF;
	
	IF $DIRECT > 0 THEN
		SET $DIRECT_YN = 'N';
	ELSE
		SET $DIRECT_YN = 'Y';
	END IF;


	INSERT INTO status_conversion_TEST(sdate,ordcode,userid,product,gubun,sitecode,media_id,media_code,convtype,ordcnt,ordpcnt,ordprice
		, mcgb, in_hour, DIRECT, REGDATE, MOBON_YN)
	VALUES($PARTDT,$ORDCODE,$USERID,$ADPRODUCT,$ADGUBUN,$SITECODE,$MEDIA_ID,$MEDIA_CODE,$actgb,1,$ORDQTY,$ORDPRICE
		, $MCGB, $IN_HOUR, $DIRECT, $REGDATE, $MOBON_YN)
	ON DUPLICATE KEY UPDATE ordcnt = 1;


	SET $TRGT_ORDER_AMT = 0;
	SET $TRGT_ORDER_CNT = 0;
	SET $TRGT_ORDER_QY = 0;
	IF $ADGUBUN='04' OR $ADGUBUN='10' OR $ADGUBUN='16' OR $ADGUBUN='17' THEN	-- ('CW','RC','SR','SP') 04, 10, 17, 16
		SET $TRGT_ORDER_AMT = $ORDPRICE;
		SET $TRGT_ORDER_CNT = 1;
		SET $TRGT_ORDER_QY = $ORDQTY;
	END IF;
	INSERT INTO MOB_CNVRS_STATS(STATS_DTTM, PLTFOM_TP_CODE, ADVRTS_PRDT_CODE, ADVRTS_TP_CODE, SITE_CODE, MEDIA_SCRIPT_NO, ORDER_NO, EXL_ITL_YN
		, CLICK_TP, SESION_SELNG_YN, DIRECT_YN, MOB_ORDER_YN, CNVRS_TP_CODE
		, ORDER_AMT, ORDER_CNT, ORDER_QY
		, TRGT_ORDER_AMT, TRGT_ORDER_CNT, TRGT_ORDER_QY
		, REG_USER_ID, REG_DTTM)
	VALUES($PARTDT, $PLATFORM, $PRODUCT, $ADGUBUN, $SITECODE, $MEDIA_CODE, $ORDERCODE, $EXL_ITL_YN
		, '', '', '', $MOBON_YN, ''
		, $ORDPRICE, 1, $ORDQTY
		, $TRGT_ORDER_AMT, $TRGT_ORDER_CNT, $TRGT_ORDER_QY
		, 'ADMIN', NOW())
	ON DUPLICATE KEY UPDATE ALT_DTTM = NOW();

END$$

DELIMITER ;
