
DROP TABLE MOB_ADVER_HH_STATS;
CREATE TABLE `MOB_ADVER_HH_STATS` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `STATS_HH` VARCHAR(2) NOT NULL COMMENT '통계시간|통계의 시간을 기록|00 ~ 23|',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `ADVER_ID` VARCHAR(30) NOT NULL COMMENT '광고주ID|광고주 ID|admember.userid|',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `TOT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '총노출횟수|총 노출 횟수||',
  `PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '지면노출횟수|지면 노출 횟수||',
  `CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '클릭횟수|클릭 횟수||',
  `ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '광고금액|광고 금액||',
  `MEDIA_PYMNT_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '매체지급금액|매체지급금액||',
  `TRGT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟노출횟수|타겟 노출 횟수||',
  `TRGT_PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟지면노출횟수|타겟지면 노출 횟수||',
  `TRGT_CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타켓클릭횟수|타겟 클릭 횟수||',
  `TRGT_ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '타겟광고금액|타겟 광고금액||',
  `RETRN_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '반송횟수|반송 광고에 대한 횟수||',
  `AVAL_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '유효횟수|유효 광고에 대한 횟수||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`STATS_HH`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`ADVER_ID`,`ITL_TP_CODE`),
  KEY `MOB_ADVER_HH_STATS_X01` (`ADVER_ID`,`STATS_DTTM`,`STATS_HH`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온광고주별시간통계|모비온광고주별시간통계||'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_ADVER_HH_STATS_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_ADVER_HH_STATS_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_ADVER_HH_STATS_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_ADVER_HH_STATS_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE MOB_ADVER_MEDIA_HH_STATS;
CREATE TABLE `MOB_ADVER_MEDIA_HH_STATS` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `STATS_HH` VARCHAR(2) NOT NULL COMMENT '통계시간|통계의 시간을 기록|00 ~ 23|',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `ADVER_ID` VARCHAR(30) NOT NULL COMMENT '광고주ID|광고주 ID|admember.userid|',
  `MEDIA_SCRIPT_NO` INT(11) NOT NULL COMMENT '매체스크립트번호|매체스크립트 번호|media_script.no|',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `TOT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '총노출횟수|총 노출 횟수||',
  `PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '지면노출횟수|지면 노출 횟수||',
  `CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '클릭횟수|클릭 횟수||',
  `ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '광고금액|광고 금액||',
  `MEDIA_PYMNT_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '매체지급금액|매체지급금액||',
  `TRGT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟노출횟수|타겟 노출 횟수||',
  `TRGT_PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟지면노출횟수|타겟지면 노출 횟수||',
  `TRGT_CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타켓클릭횟수|타겟 클릭 횟수||',
  `TRGT_ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '타겟광고금액|타겟 광고금액||',
  `RETRN_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '반송횟수|반송 광고에 대한 횟수||',
  `AVAL_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '유효횟수|유효 광고에 대한 횟수||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`STATS_HH`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`ADVER_ID`,`MEDIA_SCRIPT_NO`,`ITL_TP_CODE`),
  KEY `MOB_ADVER_MEDIA_STATS_X01` (`MEDIA_SCRIPT_NO`,`STATS_DTTM`),
  KEY `MOB_ADVER_MEDIA_STATS_X02` (`ADVER_ID`,`STATS_DTTM`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온광고주매체시간통계|모비온광고주매체시간통계||'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_ADVER_MEDIA_HH_STATS_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_ADVER_MEDIA_HH_STATS_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_ADVER_MEDIA_HH_STATS_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_ADVER_MEDIA_HH_STATS_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE `MOB_ADVER_MEDIA_STATS`;
CREATE TABLE `MOB_ADVER_MEDIA_STATS` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `ADVER_ID` VARCHAR(30) NOT NULL COMMENT '광고주ID|광고주 ID|admember.userid|',
  `MEDIA_SCRIPT_NO` INT(11) NOT NULL COMMENT '매체스크립트번호|매체스크립트 번호|media_script.no|',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `TOT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '총노출횟수|총 노출 횟수||',
  `PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '지면노출횟수|지면 노출 횟수||',
  `CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '클릭횟수|클릭 횟수||',
  `ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '광고금액|광고 금액||',
  `MEDIA_PYMNT_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '매체지급금액|매체지급금액||',
  `TRGT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟노출횟수|타겟 노출 횟수||',
  `TRGT_PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟지면노출횟수|타겟지면 노출 횟수||',
  `TRGT_CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타켓클릭횟수|타겟 클릭 횟수||',
  `TRGT_ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '타겟광고금액|타겟 광고금액||',
  `RETRN_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '반송횟수|반송 광고에 대한 횟수||',
  `AVAL_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '유효횟수|유효 광고에 대한 횟수||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`ADVER_ID`,`MEDIA_SCRIPT_NO`,`ITL_TP_CODE`),
  KEY `MOB_ADVER_MEDIA_STATS_X01` (`MEDIA_SCRIPT_NO`,`STATS_DTTM`),
  KEY `MOB_ADVER_MEDIA_STATS_X02` (`ADVER_ID`,`STATS_DTTM`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온광고주매체통계|모비온광고주매체통계||'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_ADVER_MEDIA_STATS_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_ADVER_MEDIA_STATS_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_ADVER_MEDIA_STATS_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_ADVER_MEDIA_STATS_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE `MOB_ADVER_STATS`;
CREATE TABLE `MOB_ADVER_STATS` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `ADVER_ID` VARCHAR(30) NOT NULL COMMENT '광고주ID|광고주 ID|admember.userid|',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `TOT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '총노출횟수|총 노출 횟수||',
  `PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '지면노출횟수|지면 노출 횟수||',
  `CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '클릭횟수|클릭 횟수||',
  `ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '광고금액|광고 금액||',
  `MEDIA_PYMNT_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '매체지급금액|매체지급금액||',
  `TRGT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟노출횟수|타겟 노출 횟수||',
  `TRGT_PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟지면노출횟수|타겟지면 노출 횟수||',
  `TRGT_CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타켓클릭횟수|타겟 클릭 횟수||',
  `TRGT_ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '타겟광고금액|타겟 광고금액||',
  `RETRN_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '반송횟수|반송 광고에 대한 횟수||',
  `AVAL_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '유효횟수|유효 광고에 대한 횟수||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`ADVER_ID`,`ITL_TP_CODE`),
  KEY `MOB_ADVER_STATS_X01` (`ADVER_ID`,`STATS_DTTM`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온매체별통계|모비온매체별통계||'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_ADVER_STATS_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_ADVER_STATS_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_ADVER_STATS_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_ADVER_STATS_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE MOB_CAMP_HH_STATS;
CREATE TABLE `MOB_CAMP_HH_STATS` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `STATS_HH` VARCHAR(2) NOT NULL COMMENT '통계시간|통계의 시간을 기록|00 ~ 23|',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `SITE_CODE` VARCHAR(40) NOT NULL COMMENT '사이트코드|사이트 코드|adsite.site_code|',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `TOT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '총노출횟수|총 노출 횟수||',
  `CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '클릭횟수|클릭 횟수||',
  `ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '광고금액|광고 금액||',
  `TRGT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟노출횟수|타겟 노출 횟수||',
  `TRGT_PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟지면노출횟수|타겟지면 노출 횟수||',
  `TRGT_CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타켓클릭횟수|타겟 클릭 횟수||',
  `TRGT_ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '타겟광고금액|타겟 광고금액||',
  `RETRN_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '반송횟수|반송 광고에 대한 횟수||',
  `AVAL_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '유효횟수|유효 광고에 대한 횟수||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`STATS_HH`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`SITE_CODE`,`ITL_TP_CODE`),
  KEY `MOB_CAMP_STATS_X01` (`SITE_CODE`,`STATS_DTTM`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온캠페인시간통계|모비온캠페인시간통계||'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_CAMP_HH_STATS_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_CAMP_HH_STATS_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_CAMP_HH_STATS_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_CAMP_HH_STATS_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE MOB_CAMP_MEDIA_HH_STATS;
CREATE TABLE `MOB_CAMP_MEDIA_HH_STATS` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `STATS_HH` VARCHAR(2) NOT NULL COMMENT '통계시간|통계의 시간을 기록|00 ~ 23|',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `SITE_CODE` VARCHAR(40) NOT NULL COMMENT '사이트코드|사이트 코드|adsite.site_code|',
  `MEDIA_SCRIPT_NO` INT(11) NOT NULL COMMENT '매체스크립트번호|매체스크립트 번호|media_script.no|',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `TOT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '총노출횟수|총 노출 횟수||',
  `CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '클릭횟수|클릭 횟수||',
  `ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '광고금액|광고 금액||',
  `MEDIA_PYMNT_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '매체지급금액|매체지급금액||',
  `TRGT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟노출횟수|타겟 노출 횟수||',
  `TRGT_PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟지면노출횟수|타겟지면 노출 횟수||',
  `TRGT_CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타켓클릭횟수|타겟 클릭 횟수||',
  `TRGT_ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '타겟광고금액|타겟 광고금액||',
  `RETRN_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '반송횟수|반송 광고에 대한 횟수||',
  `AVAL_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '유효횟수|유효 광고에 대한 횟수||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`STATS_HH`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`SITE_CODE`,`MEDIA_SCRIPT_NO`,`ITL_TP_CODE`),
  KEY `MOB_CAMP_MEDIA_STATS_X01` (`SITE_CODE`,`STATS_DTTM`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온캠페인매체시간통계|모비온캠페인매체시간통계||'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_CAMP_MEDIA_HH_STATS_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_CAMP_MEDIA_HH_STATS_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_CAMP_MEDIA_HH_STATS_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_CAMP_MEDIA_HH_STATS_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE MOB_CAMP_MEDIA_STATS;
CREATE TABLE `MOB_CAMP_MEDIA_STATS` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `SITE_CODE` VARCHAR(40) NOT NULL COMMENT '사이트코드|사이트 코드|adsite.site_code|',
  `MEDIA_SCRIPT_NO` INT(11) NOT NULL COMMENT '매체스크립트번호|매체스크립트 번호|media_script.no|',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `TOT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '총노출횟수|총 노출 횟수||',
  `CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '클릭횟수|클릭 횟수||',
  `ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '광고금액|광고 금액||',
  `MEDIA_PYMNT_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '매체지급금액|매체지급금액||',
  `TRGT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟노출횟수|타겟 노출 횟수||',
  `TRGT_PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟지면노출횟수|타겟지면 노출 횟수||',
  `TRGT_CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타켓클릭횟수|타겟 클릭 횟수||',
  `TRGT_ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '타겟광고금액|타겟 광고금액||',
  `RETRN_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '반송횟수|반송 광고에 대한 횟수||',
  `AVAL_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '유효횟수|유효 광고에 대한 횟수||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`SITE_CODE`,`MEDIA_SCRIPT_NO`,`ITL_TP_CODE`),
  KEY `MOB_CAMP_MEDIA_STATS_X01` (`SITE_CODE`,`STATS_DTTM`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온캠페인매체통계|모비온캠페인매체통계||'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_CAMP_MEDIA_STATS_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_CAMP_MEDIA_STATS_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_CAMP_MEDIA_STATS_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_CAMP_MEDIA_STATS_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE MOB_CAMP_STATS;
CREATE TABLE `MOB_CAMP_STATS` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `SITE_CODE` VARCHAR(40) NOT NULL COMMENT '사이트코드|사이트 코드|adsite.site_code|',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `TOT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '총노출횟수|총 노출 횟수||',
  `CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '클릭횟수|클릭 횟수||',
  `ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '광고금액|광고 금액||',
  `TRGT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟노출횟수|타겟 노출 횟수||',
  `TRGT_PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟지면노출횟수|타겟지면 노출 횟수||',
  `TRGT_CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타켓클릭횟수|타겟 클릭 횟수||',
  `TRGT_ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '타겟광고금액|타겟 광고금액||',
  `RETRN_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '반송횟수|반송 광고에 대한 횟수||',
  `AVAL_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '유효횟수|유효 광고에 대한 횟수||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`SITE_CODE`,`ITL_TP_CODE`),
  KEY `MOB_CAMP_STATS_X01` (`SITE_CODE`,`STATS_DTTM`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온캠페인통계|모비온캠페인통계||'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_CAMP_STATS_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_CAMP_STATS_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_CAMP_STATS_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_CAMP_STATS_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE MOB_CNVRS_HH_STATS;
CREATE TABLE `MOB_CNVRS_HH_STATS` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `STATS_HH` VARCHAR(2) NOT NULL COMMENT '통계시간|통계의 시간을 기록|00 ~ 23|',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `SITE_CODE` VARCHAR(40) NOT NULL COMMENT '사이트코드|사이트 코드|adsite.site_code|',
  `MEDIA_SCRIPT_NO` INT(11) NOT NULL COMMENT '매체스크립트번호|매체스크립트 번호|media_script.no|',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `SESION_SELNG_YN` VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '세션매출여부|세션 매출여부, 기본값 N|Y:세션매출, N:세션아님|',
  `DIRECT_YN` VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '직접여부|직간접 여부, 기본값 N|Y:직접, N:간접|',
  `CLICK_TP` VARCHAR(1) NOT NULL DEFAULT 'V' COMMENT '클릭부분|클릭 구분, 기본값 노출|V:노출, C:클릭|',
  `CNVRS_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '전환구분코드|전환구분코드, 기본값 01|MOBON_COM_CODE.CNVRS_TP_CODE|\r\n	',
  `MOB_ORDER_YN` VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '모비온주문여부|모비온 주문여부, 기본값 N|Y:모비온 주문, N:모비온 주문아님|',
  `ORDER_AMT` INT(11) NOT NULL DEFAULT 0 COMMENT '주문금액|주문금액||',
  `ORDER_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '주문횟수|주문횟수||',
  `ORDER_QY` INT(11) NOT NULL DEFAULT 0 COMMENT '주문수량|주문수량||',
  `TRGT_ORDER_AMT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟주문금액|타겟팅 주문금액||',
  `TRGT_ORDER_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟주문횟수|타겟팅 주문횟수||',
  `TRGT_ORDER_QY` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟주문수량|타겟팅 주문수량||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`STATS_HH`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`SITE_CODE`,`MEDIA_SCRIPT_NO`,`ITL_TP_CODE`,`SESION_SELNG_YN`,`DIRECT_YN`,`CLICK_TP`,`CNVRS_TP_CODE`,`MOB_ORDER_YN`),
  KEY `MOB_CNVRS_STATS_X01` (`MEDIA_SCRIPT_NO`,`STATS_DTTM`),
  KEY `MOB_CNVRS_STATS_X02` (`SITE_CODE`,`STATS_DTTM`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온전환통계|모비온전환통계||'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_CNVRS_HH_STATS_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_CNVRS_HH_STATS_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_CNVRS_HH_STATS_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_CNVRS_HH_STATS_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE MOB_CNVRS_NCL;
CREATE TABLE `MOB_CNVRS_NCL` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `ADVER_ID` VARCHAR(30) NOT NULL COMMENT '광고주ID|광고주 ID|admember.userid|',
  `ORDER_NO` VARCHAR(35) NOT NULL COMMENT '주문번호|주문번호||',
  `CLICK_TP` VARCHAR(1) NOT NULL DEFAULT 'V' COMMENT '클릭부분|클릭 구분, 기본값 노출|V:노출, C:클릭|',
  `SESION_SELNG_YN` VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '세션매출여부|세션 매출여부, 기본값 N|Y:세션매출, N:세션아님|',
  `DIRECT_YN` VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '직접여부|직간접 여부, 기본값 N|Y:직접, N:간접|',
  `MOB_ORDER_YN` VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '모비온주문여부|모비온 주문여부, 기본값 N|Y:모비온 주문, N:모비온 주문아님|',
  `CNVRS_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '전환구분코드|전환구분코드, 기본값 01|MOBON_COM_CODE.CNVRS_TP_CODE|\r\n	',
  `ORDER_AMT` INT(11) NOT NULL DEFAULT 0 COMMENT '주문금액|주문금액||',
  `ORDER_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '주문횟수|주문횟수||',
  `ORDER_QY` INT(11) NOT NULL DEFAULT 0 COMMENT '주문수량|주문수량||',
  `TRGT_ORDER_AMT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟주문금액|타겟팅 주문금액||',
  `TRGT_ORDER_QY` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟주문수량|타겟팅 주문수량||',
  `MEDIA_SCRIPT_NO` INT(11) NOT NULL COMMENT '매체스크립트번호|매체스크립트 번호|media_script.no|',
  `SITE_CODE` VARCHAR(40) NOT NULL COMMENT '사이트코드|사이트 코드|adsite.site_code|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`ADVER_ID`,`ORDER_NO`),
  KEY `MOB_CNVRS_STATS_X01` (`ORDER_NO`),
  KEY `MOB_CNVRS_STATS_X02` (`ADVER_ID`,`STATS_DTTM`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온전환통계|모비온전환통계||'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_CNVRS_NCL_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_CNVRS_NCL_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_CNVRS_NCL_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_CNVRS_NCL_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE MOB_CNVRS_STATS;
CREATE TABLE `MOB_CNVRS_STATS` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `SITE_CODE` VARCHAR(40) NOT NULL COMMENT '사이트코드|사이트 코드|adsite.site_code|',
  `MEDIA_SCRIPT_NO` INT(11) NOT NULL COMMENT '매체스크립트번호|매체스크립트 번호|media_script.no|',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `SESION_SELNG_YN` VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '세션매출여부|세션 매출여부, 기본값 N|Y:세션매출, N:세션아님|',
  `DIRECT_YN` VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '직접여부|직간접 여부, 기본값 N|Y:직접, N:간접|',
  `CLICK_TP` VARCHAR(1) NOT NULL DEFAULT 'V' COMMENT '클릭부분|클릭 구분, 기본값 노출|V:노출, C:클릭|',
  `CNVRS_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '전환구분코드|전환구분코드, 기본값 01|MOBON_COM_CODE.CNVRS_TP_CODE|\r\n	',
  `MOB_ORDER_YN` VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '모비온주문여부|모비온 주문여부, 기본값 N|Y:모비온 주문, N:모비온 주문아님|',
  `ORDER_AMT` INT(11) NOT NULL DEFAULT 0 COMMENT '주문금액|주문금액||',
  `ORDER_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '주문횟수|주문횟수||',
  `ORDER_QY` INT(11) NOT NULL DEFAULT 0 COMMENT '주문수량|주문수량||',
  `TRGT_ORDER_AMT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟주문금액|타겟팅 주문금액||',
  `TRGT_ORDER_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟주문횟수|타겟팅 주문횟수||',
  `TRGT_ORDER_QY` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟주문수량|타겟팅 주문수량||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`SITE_CODE`,`MEDIA_SCRIPT_NO`,`ITL_TP_CODE`,`SESION_SELNG_YN`,`DIRECT_YN`,`CLICK_TP`,`CNVRS_TP_CODE`,`MOB_ORDER_YN`),
  KEY `MOB_CNVRS_STATS_X01` (`MEDIA_SCRIPT_NO`,`STATS_DTTM`),
  KEY `MOB_CNVRS_STATS_X02` (`SITE_CODE`,`STATS_DTTM`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온전환통계|모비온전환통계||'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_CNVRS_STATS_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_CNVRS_STATS_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_CNVRS_STATS_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_CNVRS_STATS_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE MOB_COM_HH_STATS_INFO;
CREATE TABLE `MOB_COM_HH_STATS_INFO` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `STATS_HH` VARCHAR(2) NOT NULL COMMENT '통계시간|통계의 시간을 기록|00 ~ 23|',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `TOT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '총노출횟수|총 노출 횟수||',
  `PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '지면노출횟수|지면 노출 횟수||',
  `CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '클릭횟수|클릭 횟수||',
  `ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '광고금액|광고 금액||',
  `MEDIA_PYMNT_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '매체지급금액|매체지급금액||',
  `TRGT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟노출횟수|타겟 노출 횟수||',
  `TRGT_PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟지면노출횟수|타겟지면 노출 횟수||',
  `TRGT_CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타켓클릭횟수|타겟 클릭 횟수||',
  `TRGT_ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '타겟광고금액|타겟 광고금액||',
  `RETRN_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '반송횟수|반송 광고에 대한 횟수||',
  `AVAL_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '유효횟수|유효 광고에 대한 횟수||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`STATS_HH`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`ITL_TP_CODE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온공통시간통계|모비온 시간 통계 공통 정보|통계 기본 데이터 통계에 사용할 데이터는 미리 저장되어야 함.|'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_COM_HH_STATS_INFO_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_COM_HH_STATS_INFO_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_COM_HH_STATS_INFO_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_COM_HH_STATS_INFO_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE MOB_COM_STATS_INFO;
CREATE TABLE `MOB_COM_STATS_INFO` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `TOT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '총노출횟수|총 노출 횟수||',
  `PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '지면노출횟수|지면 노출 횟수||',
  `CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '클릭횟수|클릭 횟수||',
  `ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '광고금액|광고 금액||',
  `MEDIA_PYMNT_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '매체지급금액|매체지급금액||',
  `TRGT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟노출횟수|타겟 노출 횟수||',
  `TRGT_PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟지면노출횟수|타겟지면 노출 횟수||',
  `TRGT_CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타켓클릭횟수|타겟 클릭 횟수||',
  `TRGT_ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '타겟광고금액|타겟 광고금액||',
  `RETRN_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '반송횟수|반송 광고에 대한 횟수||',
  `AVAL_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '유효횟수|유효 광고에 대한 횟수||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`ITL_TP_CODE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온통계공통|모비온 통계 공통 정보|통계 기본 데이터 통계에 사용할 데이터는 미리 저장되어야 함.|'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_COM_STATS_INFO_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_COM_STATS_INFO_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_COM_STATS_INFO_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_COM_STATS_INFO_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE MOB_KWRD_STATS;
CREATE TABLE `MOB_KWRD_STATS` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `SITE_CODE` VARCHAR(40) NOT NULL COMMENT '사이트코드|사이트 코드|adsite.site_code|',
  `MEDIA_SCRIPT_NO` INT(11) NOT NULL COMMENT '매체스크립트번호|매체스크립트 번호|media_script.no|',
  `KWRD_APPN_NO` BIGINT(20) UNSIGNED NOT NULL COMMENT '키워드지정번호|키워드지정 고유번호||',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `TOT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '총노출횟수|총 노출 횟수||',
  `CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '클릭횟수|클릭 횟수||',
  `ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '광고금액|광고 금액||',
  `MEDIA_PYMNT_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '매체지급금액|매체지급금액||',
  `TRGT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟노출횟수|타겟 노출 횟수||',
  `TRGT_PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟지면노출횟수|타겟지면 노출 횟수||',
  `TRGT_CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타켓클릭횟수|타겟 클릭 횟수||',
  `TRGT_ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '타겟광고금액|타겟 광고금액||',
  `RETRN_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '반송횟수|반송 광고에 대한 횟수||',
  `AVAL_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '유효횟수|유효 광고에 대한 횟수||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`SITE_CODE`,`MEDIA_SCRIPT_NO`,`KWRD_APPN_NO`,`ITL_TP_CODE`),
  KEY `MOB_KWRD_STATS_X01` (`SITE_CODE`,`STATS_DTTM`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온키워드통계|모비온키워드통계||'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_KWRD_STATS_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_KWRD_STATS_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_KWRD_STATS_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_KWRD_STATS_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE MOB_MEDIA_HH_STATS;
CREATE TABLE `MOB_MEDIA_HH_STATS` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `STATS_HH` VARCHAR(2) NOT NULL COMMENT '통계시간|통계의 시간을 기록|00 ~ 23|',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `MEDIA_ID` VARCHAR(30) NOT NULL COMMENT '매체아이디|매체 아이디admember.userid|',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `TOT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '총노출횟수|총 노출 횟수||',
  `PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '지면노출횟수|지면 노출 횟수||',
  `CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '클릭횟수|클릭 횟수||',
  `ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '광고금액|광고 금액||',
  `MEDIA_PYMNT_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '매체지급금액|매체지급금액||',
  `TRGT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟노출횟수|타겟 노출 횟수||',
  `TRGT_PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟지면노출횟수|타겟지면 노출 횟수||',
  `TRGT_CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타켓클릭횟수|타겟 클릭 횟수||',
  `TRGT_ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '타겟광고금액|타겟 광고금액||',
  `RETRN_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '반송횟수|반송 광고에 대한 횟수||',
  `AVAL_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '유효횟수|유효 광고에 대한 횟수||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`STATS_HH`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`MEDIA_ID`,`ITL_TP_CODE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온매체사시간통계|모비온매체사시간통계||'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_MEDIA_HH_STATS_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_MEDIA_HH_STATS_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_MEDIA_HH_STATS_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_MEDIA_HH_STATS_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE MOB_MEDIA_SCRIPT_HH_STATS;
CREATE TABLE `MOB_MEDIA_SCRIPT_HH_STATS` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `STATS_HH` VARCHAR(2) NOT NULL COMMENT '통계시간|통계의 시간을 기록|00 ~ 23|',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `MEDIA_SCRIPT_NO` INT(11) NOT NULL COMMENT '매체스크립트번호|매체스크립트 번호|media_script.no|',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `MEDIA_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '매체구분코드|매체구분코드, 기본값 01||MOBON_COM_CODE.MEDIA_TP_CODE|',
  `MEDIA_ID` VARCHAR(30) NOT NULL COMMENT '매체아이디|매체 아이디admember.userid|',
  `TOT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '총노출횟수|총 노출 횟수||',
  `PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '지면노출횟수|지면 노출 횟수||',
  `CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '클릭횟수|클릭 횟수||',
  `ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '광고금액|광고 금액||',
  `MEDIA_PYMNT_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '매체지급금액|매체지급금액||',
  `TRGT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟노출횟수|타겟 노출 횟수||',
  `TRGT_PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟지면노출횟수|타겟지면 노출 횟수||',
  `TRGT_CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타켓클릭횟수|타겟 클릭 횟수||',
  `TRGT_ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '타겟광고금액|타겟 광고금액||',
  `RETRN_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '반송횟수|반송 광고에 대한 횟수||',
  `AVAL_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '유효횟수|유효 광고에 대한 횟수||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`STATS_HH`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`MEDIA_SCRIPT_NO`,`ITL_TP_CODE`),
  KEY `MOB_MEDIA_SCRIPT_STATS_X01` (`MEDIA_ID`,`STATS_DTTM`),
  KEY `MOB_MEDIA_SCRIPT_STATS_X02` (`MEDIA_SCRIPT_NO`,`STATS_DTTM`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온매체스크립트시간통계|모비온매체스크립트시간통계||'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_MEDIA_SCRIPT_HH_STATS_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_MEDIA_SCRIPT_HH_STATS_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_MEDIA_SCRIPT_HH_STATS_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_MEDIA_SCRIPT_HH_STATS_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE MOB_MEDIA_SCRIPT_STATS;
CREATE TABLE `MOB_MEDIA_SCRIPT_STATS` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `MEDIA_SCRIPT_NO` INT(11) NOT NULL COMMENT '매체스크립트번호|매체스크립트 번호|media_script.no|',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `MEDIA_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '매체구분코드|매체구분코드, 기본값 01||MOBON_COM_CODE.MEDIA_TP_CODE|',
  `MEDIA_ID` VARCHAR(30) NOT NULL COMMENT '매체아이디|매체 아이디admember.userid|',
  `TOT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '총노출횟수|총 노출 횟수||',
  `PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '지면노출횟수|지면 노출 횟수||',
  `CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '클릭횟수|클릭 횟수||',
  `ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '광고금액|광고 금액||',
  `MEDIA_PYMNT_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '매체지급금액|매체지급금액||',
  `TRGT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟노출횟수|타겟 노출 횟수||',
  `TRGT_PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟지면노출횟수|타겟지면 노출 횟수||',
  `TRGT_CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타켓클릭횟수|타겟 클릭 횟수||',
  `TRGT_ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '타겟광고금액|타겟 광고금액||',
  `RETRN_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '반송횟수|반송 광고에 대한 횟수||',
  `AVAL_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '유효횟수|유효 광고에 대한 횟수||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`MEDIA_SCRIPT_NO`,`ITL_TP_CODE`),
  KEY `MOB_MEDIA_SCRIPT_STATS_X01` (`MEDIA_ID`,`STATS_DTTM`),
  KEY `MOB_MEDIA_SCRIPT_STATS_X02` (`MEDIA_SCRIPT_NO`,`STATS_DTTM`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온매체스크립트통계|모비온매체스크립트통계||'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_MEDIA_SCRIPT_STATS_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_MEDIA_SCRIPT_STATS_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_MEDIA_SCRIPT_STATS_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_MEDIA_SCRIPT_STATS_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;

DROP TABLE MOB_MEDIA_STATS;
CREATE TABLE `MOB_MEDIA_STATS` (
  `STATS_DTTM` INT(11) NOT NULL COMMENT '통계일자|통계의 일자를 기록||',
  `PLTFOM_TP_CODE` VARCHAR(2) NOT NULL COMMENT '플랫폼구분코드|플랫폼 구분 코드|MOBON_COM_CODE.PLTFOM_TP_CODE|',
  `ADVRTS_PRDT_CODE` VARCHAR(2) NOT NULL COMMENT '광고상품코드|광고 상품 코드|MOBON_COM_CODE.ADVRTS_PRDT_CODE|',
  `ADVRTS_TP_CODE` VARCHAR(2) NOT NULL COMMENT '광고구분코드|광고 구분 코드|MOBON_COM_CODE.ADVRTS_TP_CODE|',
  `MEDIA_ID` VARCHAR(30) NOT NULL COMMENT '매체아이디|매체 아이디admember.userid|',
  `ITL_TP_CODE` VARCHAR(2) NOT NULL DEFAULT '01' COMMENT '연동구분코드|연동 구분 코드, 기본값 ''01''|MOBON_COM_CODE.ITL_TP_CODE|',
  `TOT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '총노출횟수|총 노출 횟수||',
  `PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '지면노출횟수|지면 노출 횟수||',
  `CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '클릭횟수|클릭 횟수||',
  `ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '광고금액|광고 금액||',
  `MEDIA_PYMNT_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '매체지급금액|매체지급금액||',
  `TRGT_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟노출횟수|타겟 노출 횟수||',
  `TRGT_PAR_EPRS_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타겟지면노출횟수|타겟지면 노출 횟수||',
  `TRGT_CLICK_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '타켓클릭횟수|타겟 클릭 횟수||',
  `TRGT_ADVRTS_AMT` DECIMAL(13,2) NOT NULL DEFAULT 0.00 COMMENT '타겟광고금액|타겟 광고금액||',
  `RETRN_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '반송횟수|반송 광고에 대한 횟수||',
  `AVAL_CNT` INT(11) NOT NULL DEFAULT 0 COMMENT '유효횟수|유효 광고에 대한 횟수||',
  `REG_USER_ID` VARCHAR(30) NOT NULL DEFAULT 'ADMIN' COMMENT '등록사용자ID|등록사용자ID를 기록|admember.userid|',
  `REG_DTTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일자|등록시간을 기록||',
  `ALT_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '수정사용자ID|수정사용자ID를 기록|admember.userid|',
  `ALT_DTTM` DATETIME DEFAULT NULL COMMENT '수정일자|수정시간을 기록||',
  PRIMARY KEY (`STATS_DTTM`,`PLTFOM_TP_CODE`,`ADVRTS_PRDT_CODE`,`ADVRTS_TP_CODE`,`MEDIA_ID`,`ITL_TP_CODE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='모비온매체별통계|모비온매체별통계||'
 PARTITION BY RANGE (`STATS_DTTM`)
(
 PARTITION `MOB_MEDIA_STATS_201805` VALUES LESS THAN (20180601) ENGINE = INNODB,
 PARTITION `MOB_MEDIA_STATS_201806` VALUES LESS THAN (20180701) ENGINE = INNODB,
 PARTITION `MOB_MEDIA_STATS_201807` VALUES LESS THAN (20180801) ENGINE = INNODB,
 PARTITION `MOB_MEDIA_STATS_201808` VALUES LESS THAN (20180901) ENGINE = INNODB
 )
;


